/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`delete_agent`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteAgentError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_agent`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAgentError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_agent_field`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAgentFieldError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_agent_pool`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAgentPoolError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_all_agents`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAllAgentsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_authorized_info`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAuthorizedInfoError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_build_configuration_run_policy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetBuildConfigurationRunPolicyError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_compatible_build_types`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCompatibleBuildTypesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_enabled_info`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetEnabledInfoError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_incompatible_build_types`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetIncompatibleBuildTypesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_agent_field`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetAgentFieldError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_agent_pool`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetAgentPoolError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_authorized_info`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetAuthorizedInfoError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_build_configuration_run_policy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetBuildConfigurationRunPolicyError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_enabled_info`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetEnabledInfoError {
    UnknownValue(serde_json::Value),
}


pub async fn delete_agent(configuration: &configuration::Configuration, agent_locator: &str) -> Result<(), Error<DeleteAgentError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_locator = agent_locator;

    let uri_str = format!("{}/app/rest/agents/{agentLocator}", configuration.base_path, agentLocator=crate::apis::urlencode(p_path_agent_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteAgentError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_agent(configuration: &configuration::Configuration, agent_locator: &str, fields: Option<&str>) -> Result<models::Agent, Error<GetAgentError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_locator = agent_locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/agents/{agentLocator}", configuration.base_path, agentLocator=crate::apis::urlencode(p_path_agent_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Agent`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Agent`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAgentError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_agent_field(configuration: &configuration::Configuration, agent_locator: &str, field: &str) -> Result<String, Error<GetAgentFieldError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_locator = agent_locator;
    let p_path_field = field;

    let uri_str = format!("{}/app/rest/agents/{agentLocator}/{field}", configuration.base_path, agentLocator=crate::apis::urlencode(p_path_agent_locator), field=crate::apis::urlencode(p_path_field));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAgentFieldError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_agent_pool(configuration: &configuration::Configuration, agent_locator: &str, fields: Option<&str>) -> Result<models::AgentPool, Error<GetAgentPoolError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_locator = agent_locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/agents/{agentLocator}/pool", configuration.base_path, agentLocator=crate::apis::urlencode(p_path_agent_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AgentPool`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AgentPool`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAgentPoolError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_all_agents(configuration: &configuration::Configuration, locator: Option<&str>, fields: Option<&str>) -> Result<models::Agents, Error<GetAllAgentsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_locator = locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/agents", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_locator {
        req_builder = req_builder.query(&[("locator", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Agents`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Agents`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAllAgentsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_authorized_info(configuration: &configuration::Configuration, agent_locator: &str, fields: Option<&str>) -> Result<models::AuthorizedInfo, Error<GetAuthorizedInfoError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_locator = agent_locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/agents/{agentLocator}/authorizedInfo", configuration.base_path, agentLocator=crate::apis::urlencode(p_path_agent_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AuthorizedInfo`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AuthorizedInfo`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAuthorizedInfoError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_build_configuration_run_policy(configuration: &configuration::Configuration, agent_locator: &str, fields: Option<&str>) -> Result<models::CompatibilityPolicy, Error<GetBuildConfigurationRunPolicyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_locator = agent_locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/agents/{agentLocator}/compatibilityPolicy", configuration.base_path, agentLocator=crate::apis::urlencode(p_path_agent_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CompatibilityPolicy`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CompatibilityPolicy`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetBuildConfigurationRunPolicyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_compatible_build_types(configuration: &configuration::Configuration, agent_locator: &str, fields: Option<&str>) -> Result<models::BuildTypes, Error<GetCompatibleBuildTypesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_locator = agent_locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/agents/{agentLocator}/compatibleBuildTypes", configuration.base_path, agentLocator=crate::apis::urlencode(p_path_agent_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BuildTypes`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BuildTypes`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetCompatibleBuildTypesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_enabled_info(configuration: &configuration::Configuration, agent_locator: &str, fields: Option<&str>) -> Result<models::EnabledInfo, Error<GetEnabledInfoError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_locator = agent_locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/agents/{agentLocator}/enabledInfo", configuration.base_path, agentLocator=crate::apis::urlencode(p_path_agent_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnabledInfo`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnabledInfo`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetEnabledInfoError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_incompatible_build_types(configuration: &configuration::Configuration, agent_locator: &str, fields: Option<&str>) -> Result<models::Compatibilities, Error<GetIncompatibleBuildTypesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_locator = agent_locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/agents/{agentLocator}/incompatibleBuildTypes", configuration.base_path, agentLocator=crate::apis::urlencode(p_path_agent_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Compatibilities`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Compatibilities`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetIncompatibleBuildTypesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn set_agent_field(configuration: &configuration::Configuration, agent_locator: &str, field: &str, body: Option<&str>) -> Result<String, Error<SetAgentFieldError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_locator = agent_locator;
    let p_path_field = field;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/agents/{agentLocator}/{field}", configuration.base_path, agentLocator=crate::apis::urlencode(p_path_agent_locator), field=crate::apis::urlencode(p_path_field));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SetAgentFieldError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn set_agent_pool(configuration: &configuration::Configuration, agent_locator: &str, fields: Option<&str>, body: Option<models::AgentPool>) -> Result<models::AgentPool, Error<SetAgentPoolError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_locator = agent_locator;
    let p_query_fields = fields;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/agents/{agentLocator}/pool", configuration.base_path, agentLocator=crate::apis::urlencode(p_path_agent_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AgentPool`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AgentPool`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SetAgentPoolError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn set_authorized_info(configuration: &configuration::Configuration, agent_locator: &str, fields: Option<&str>, body: Option<models::AuthorizedInfo>) -> Result<models::AuthorizedInfo, Error<SetAuthorizedInfoError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_locator = agent_locator;
    let p_query_fields = fields;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/agents/{agentLocator}/authorizedInfo", configuration.base_path, agentLocator=crate::apis::urlencode(p_path_agent_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AuthorizedInfo`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AuthorizedInfo`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SetAuthorizedInfoError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn set_build_configuration_run_policy(configuration: &configuration::Configuration, agent_locator: &str, fields: Option<&str>, body: Option<models::CompatibilityPolicy>) -> Result<models::CompatibilityPolicy, Error<SetBuildConfigurationRunPolicyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_locator = agent_locator;
    let p_query_fields = fields;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/agents/{agentLocator}/compatibilityPolicy", configuration.base_path, agentLocator=crate::apis::urlencode(p_path_agent_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CompatibilityPolicy`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CompatibilityPolicy`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SetBuildConfigurationRunPolicyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn set_enabled_info(configuration: &configuration::Configuration, agent_locator: &str, fields: Option<&str>, body: Option<models::EnabledInfo>) -> Result<models::EnabledInfo, Error<SetEnabledInfoError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_locator = agent_locator;
    let p_query_fields = fields;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/agents/{agentLocator}/enabledInfo", configuration.base_path, agentLocator=crate::apis::urlencode(p_path_agent_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EnabledInfo`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EnabledInfo`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SetEnabledInfoError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

