/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`add_agent_to_agent_pool`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddAgentToAgentPoolError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`add_project_to_agent_pool`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddProjectToAgentPoolError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_agent_pool`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateAgentPoolError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_agent_pool`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteAgentPoolError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_all_projects_from_agent_pool`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteAllProjectsFromAgentPoolError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_project_from_agent_pool`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteProjectFromAgentPoolError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`generate_automatic_agent_authorization_tokens`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GenerateAutomaticAgentAuthorizationTokensError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_agent_pool_of_agent_pool`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAgentPoolOfAgentPoolError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_all_agent_pools`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAllAgentPoolsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_all_agents_from_agent_pool`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAllAgentsFromAgentPoolError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_all_projects_from_agent_pool`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAllProjectsFromAgentPoolError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_field_from_agent_pool`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetFieldFromAgentPoolError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_agent_pool_field`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetAgentPoolFieldError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_agent_pool_projects`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetAgentPoolProjectsError {
    UnknownValue(serde_json::Value),
}


pub async fn add_agent_to_agent_pool(configuration: &configuration::Configuration, agent_pool_locator: &str, fields: Option<&str>, body: Option<models::Agent>) -> Result<models::Agent, Error<AddAgentToAgentPoolError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_pool_locator = agent_pool_locator;
    let p_query_fields = fields;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/agentPools/{agentPoolLocator}/agents", configuration.base_path, agentPoolLocator=crate::apis::urlencode(p_path_agent_pool_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Agent`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Agent`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AddAgentToAgentPoolError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn add_project_to_agent_pool(configuration: &configuration::Configuration, agent_pool_locator: &str, body: Option<models::Project>) -> Result<models::Project, Error<AddProjectToAgentPoolError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_pool_locator = agent_pool_locator;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/agentPools/{agentPoolLocator}/projects", configuration.base_path, agentPoolLocator=crate::apis::urlencode(p_path_agent_pool_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Project`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Project`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AddProjectToAgentPoolError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn create_agent_pool(configuration: &configuration::Configuration, body: Option<models::AgentPool>) -> Result<models::AgentPool, Error<CreateAgentPoolError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/agentPools", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AgentPool`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AgentPool`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateAgentPoolError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delete_agent_pool(configuration: &configuration::Configuration, agent_pool_locator: &str) -> Result<(), Error<DeleteAgentPoolError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_pool_locator = agent_pool_locator;

    let uri_str = format!("{}/app/rest/agentPools/{agentPoolLocator}", configuration.base_path, agentPoolLocator=crate::apis::urlencode(p_path_agent_pool_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteAgentPoolError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delete_all_projects_from_agent_pool(configuration: &configuration::Configuration, agent_pool_locator: &str) -> Result<(), Error<DeleteAllProjectsFromAgentPoolError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_pool_locator = agent_pool_locator;

    let uri_str = format!("{}/app/rest/agentPools/{agentPoolLocator}/projects", configuration.base_path, agentPoolLocator=crate::apis::urlencode(p_path_agent_pool_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteAllProjectsFromAgentPoolError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delete_project_from_agent_pool(configuration: &configuration::Configuration, agent_pool_locator: &str, project_locator: &str) -> Result<(), Error<DeleteProjectFromAgentPoolError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_pool_locator = agent_pool_locator;
    let p_path_project_locator = project_locator;

    let uri_str = format!("{}/app/rest/agentPools/{agentPoolLocator}/projects/{projectLocator}", configuration.base_path, agentPoolLocator=crate::apis::urlencode(p_path_agent_pool_locator), projectLocator=crate::apis::urlencode(p_path_project_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteProjectFromAgentPoolError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn generate_automatic_agent_authorization_tokens(configuration: &configuration::Configuration, agent_pool_locator: &str, body: Option<models::AuthorizationTokensRequirements>) -> Result<models::Items, Error<GenerateAutomaticAgentAuthorizationTokensError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_pool_locator = agent_pool_locator;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/agentPools/{agentPoolLocator}/authorizationTokens", configuration.base_path, agentPoolLocator=crate::apis::urlencode(p_path_agent_pool_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Items`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Items`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GenerateAutomaticAgentAuthorizationTokensError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_agent_pool_of_agent_pool(configuration: &configuration::Configuration, agent_pool_locator: &str, fields: Option<&str>) -> Result<models::AgentPool, Error<GetAgentPoolOfAgentPoolError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_pool_locator = agent_pool_locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/agentPools/{agentPoolLocator}", configuration.base_path, agentPoolLocator=crate::apis::urlencode(p_path_agent_pool_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AgentPool`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AgentPool`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAgentPoolOfAgentPoolError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_all_agent_pools(configuration: &configuration::Configuration, locator: Option<&str>, fields: Option<&str>) -> Result<models::AgentPools, Error<GetAllAgentPoolsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_locator = locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/agentPools", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_locator {
        req_builder = req_builder.query(&[("locator", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AgentPools`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AgentPools`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAllAgentPoolsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_all_agents_from_agent_pool(configuration: &configuration::Configuration, agent_pool_locator: &str, locator: Option<&str>, fields: Option<&str>) -> Result<models::Agents, Error<GetAllAgentsFromAgentPoolError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_pool_locator = agent_pool_locator;
    let p_query_locator = locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/agentPools/{agentPoolLocator}/agents", configuration.base_path, agentPoolLocator=crate::apis::urlencode(p_path_agent_pool_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_locator {
        req_builder = req_builder.query(&[("locator", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Agents`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Agents`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAllAgentsFromAgentPoolError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_all_projects_from_agent_pool(configuration: &configuration::Configuration, agent_pool_locator: &str, fields: Option<&str>) -> Result<models::Projects, Error<GetAllProjectsFromAgentPoolError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_pool_locator = agent_pool_locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/agentPools/{agentPoolLocator}/projects", configuration.base_path, agentPoolLocator=crate::apis::urlencode(p_path_agent_pool_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Projects`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Projects`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAllProjectsFromAgentPoolError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_field_from_agent_pool(configuration: &configuration::Configuration, agent_pool_locator: &str, field: &str) -> Result<String, Error<GetFieldFromAgentPoolError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_pool_locator = agent_pool_locator;
    let p_path_field = field;

    let uri_str = format!("{}/app/rest/agentPools/{agentPoolLocator}/{field}", configuration.base_path, agentPoolLocator=crate::apis::urlencode(p_path_agent_pool_locator), field=crate::apis::urlencode(p_path_field));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetFieldFromAgentPoolError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn set_agent_pool_field(configuration: &configuration::Configuration, agent_pool_locator: &str, field: &str, body: Option<&str>) -> Result<String, Error<SetAgentPoolFieldError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_pool_locator = agent_pool_locator;
    let p_path_field = field;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/agentPools/{agentPoolLocator}/{field}", configuration.base_path, agentPoolLocator=crate::apis::urlencode(p_path_agent_pool_locator), field=crate::apis::urlencode(p_path_field));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SetAgentPoolFieldError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn set_agent_pool_projects(configuration: &configuration::Configuration, agent_pool_locator: &str, body: Option<models::Projects>) -> Result<models::Projects, Error<SetAgentPoolProjectsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_agent_pool_locator = agent_pool_locator;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/agentPools/{agentPoolLocator}/projects", configuration.base_path, agentPoolLocator=crate::apis::urlencode(p_path_agent_pool_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Projects`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Projects`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SetAgentPoolProjectsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

