/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`forse_terminate_instance`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ForseTerminateInstanceError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_all_cloud_images`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAllCloudImagesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_all_cloud_instances`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAllCloudInstancesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_all_cloud_profiles`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAllCloudProfilesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_cloud_image`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCloudImageError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_cloud_instance`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCloudInstanceError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_cloud_profile`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCloudProfileError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`start_instance`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StartInstanceError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`stop_instance`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StopInstanceError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`terminate_instance`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TerminateInstanceError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}


pub async fn forse_terminate_instance(configuration: &configuration::Configuration, instance_locator: &str) -> Result<(), Error<ForseTerminateInstanceError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_instance_locator = instance_locator;

    let uri_str = format!("{}/app/rest/cloud/instances/{instanceLocator}/actions/forceStop", configuration.base_path, instanceLocator=crate::apis::urlencode(p_path_instance_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ForseTerminateInstanceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_all_cloud_images(configuration: &configuration::Configuration, locator: Option<&str>, fields: Option<&str>) -> Result<models::CloudImages, Error<GetAllCloudImagesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_locator = locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/cloud/images", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_locator {
        req_builder = req_builder.query(&[("locator", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CloudImages`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CloudImages`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAllCloudImagesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_all_cloud_instances(configuration: &configuration::Configuration, locator: Option<&str>, fields: Option<&str>) -> Result<models::CloudInstances, Error<GetAllCloudInstancesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_locator = locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/cloud/instances", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_locator {
        req_builder = req_builder.query(&[("locator", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CloudInstances`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CloudInstances`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAllCloudInstancesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_all_cloud_profiles(configuration: &configuration::Configuration, locator: Option<&str>, fields: Option<&str>) -> Result<models::CloudProfiles, Error<GetAllCloudProfilesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_locator = locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/cloud/profiles", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_locator {
        req_builder = req_builder.query(&[("locator", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CloudProfiles`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CloudProfiles`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAllCloudProfilesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_cloud_image(configuration: &configuration::Configuration, image_locator: &str, fields: Option<&str>) -> Result<models::CloudImage, Error<GetCloudImageError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_image_locator = image_locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/cloud/images/{imageLocator}", configuration.base_path, imageLocator=crate::apis::urlencode(p_path_image_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CloudImage`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CloudImage`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetCloudImageError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_cloud_instance(configuration: &configuration::Configuration, instance_locator: &str, fields: Option<&str>) -> Result<models::CloudInstance, Error<GetCloudInstanceError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_instance_locator = instance_locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/cloud/instances/{instanceLocator}", configuration.base_path, instanceLocator=crate::apis::urlencode(p_path_instance_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CloudInstance`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CloudInstance`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetCloudInstanceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_cloud_profile(configuration: &configuration::Configuration, profile_locator: &str, fields: Option<&str>) -> Result<models::CloudProfile, Error<GetCloudProfileError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_profile_locator = profile_locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/cloud/profiles/{profileLocator}", configuration.base_path, profileLocator=crate::apis::urlencode(p_path_profile_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CloudProfile`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CloudProfile`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetCloudProfileError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn start_instance(configuration: &configuration::Configuration, fields: Option<&str>, body: Option<models::CloudInstance>) -> Result<(), Error<StartInstanceError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_fields = fields;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/cloud/instances", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<StartInstanceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn stop_instance(configuration: &configuration::Configuration, instance_locator: &str) -> Result<(), Error<StopInstanceError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_instance_locator = instance_locator;

    let uri_str = format!("{}/app/rest/cloud/instances/{instanceLocator}", configuration.base_path, instanceLocator=crate::apis::urlencode(p_path_instance_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<StopInstanceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn terminate_instance(configuration: &configuration::Configuration, instance_locator: &str) -> Result<(), Error<TerminateInstanceError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_instance_locator = instance_locator;

    let uri_str = format!("{}/app/rest/cloud/instances/{instanceLocator}/actions/stop", configuration.base_path, instanceLocator=crate::apis::urlencode(p_path_instance_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<TerminateInstanceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

