/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`add_group`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddGroupError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`add_role_at_scope_to_group`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddRoleAtScopeToGroupError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`add_role_to_group`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddRoleToGroupError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_group`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteGroupError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_all_groups`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAllGroupsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_group_parent_groups`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetGroupParentGroupsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_group_properties`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetGroupPropertiesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_group_property`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetGroupPropertyError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_group_role_at_scope`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetGroupRoleAtScopeError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_group_roles`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetGroupRolesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_user_group_of_group`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetUserGroupOfGroupError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`remove_group_property`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RemoveGroupPropertyError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`remove_role_at_scope_from_group`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RemoveRoleAtScopeFromGroupError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_group_parent_groups`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetGroupParentGroupsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_group_property`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetGroupPropertyError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_group_roles`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetGroupRolesError {
    UnknownValue(serde_json::Value),
}


pub async fn add_group(configuration: &configuration::Configuration, fields: Option<&str>, body: Option<models::Group>) -> Result<models::Group, Error<AddGroupError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_fields = fields;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/userGroups", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Group`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Group`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AddGroupError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn add_role_at_scope_to_group(configuration: &configuration::Configuration, group_locator: &str, role_id: &str, scope: &str) -> Result<models::RoleAssignment, Error<AddRoleAtScopeToGroupError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_locator = group_locator;
    let p_path_role_id = role_id;
    let p_path_scope = scope;

    let uri_str = format!("{}/app/rest/userGroups/{groupLocator}/roles/{roleId}/{scope}", configuration.base_path, groupLocator=crate::apis::urlencode(p_path_group_locator), roleId=crate::apis::urlencode(p_path_role_id), scope=crate::apis::urlencode(p_path_scope));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RoleAssignment`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RoleAssignment`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AddRoleAtScopeToGroupError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn add_role_to_group(configuration: &configuration::Configuration, group_locator: &str, body: Option<models::RoleAssignment>) -> Result<models::RoleAssignment, Error<AddRoleToGroupError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_locator = group_locator;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/userGroups/{groupLocator}/roles", configuration.base_path, groupLocator=crate::apis::urlencode(p_path_group_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RoleAssignment`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RoleAssignment`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AddRoleToGroupError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delete_group(configuration: &configuration::Configuration, group_locator: &str) -> Result<(), Error<DeleteGroupError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_locator = group_locator;

    let uri_str = format!("{}/app/rest/userGroups/{groupLocator}", configuration.base_path, groupLocator=crate::apis::urlencode(p_path_group_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteGroupError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_all_groups(configuration: &configuration::Configuration, fields: Option<&str>) -> Result<models::Groups, Error<GetAllGroupsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/userGroups", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Groups`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Groups`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAllGroupsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_group_parent_groups(configuration: &configuration::Configuration, group_locator: &str, fields: Option<&str>) -> Result<models::Groups, Error<GetGroupParentGroupsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_locator = group_locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/userGroups/{groupLocator}/parent-groups", configuration.base_path, groupLocator=crate::apis::urlencode(p_path_group_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Groups`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Groups`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetGroupParentGroupsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_group_properties(configuration: &configuration::Configuration, group_locator: &str, fields: Option<&str>) -> Result<models::Properties, Error<GetGroupPropertiesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_locator = group_locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/userGroups/{groupLocator}/properties", configuration.base_path, groupLocator=crate::apis::urlencode(p_path_group_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Properties`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Properties`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetGroupPropertiesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_group_property(configuration: &configuration::Configuration, group_locator: &str, name: &str) -> Result<String, Error<GetGroupPropertyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_locator = group_locator;
    let p_path_name = name;

    let uri_str = format!("{}/app/rest/userGroups/{groupLocator}/properties/{name}", configuration.base_path, groupLocator=crate::apis::urlencode(p_path_group_locator), name=crate::apis::urlencode(p_path_name));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetGroupPropertyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_group_role_at_scope(configuration: &configuration::Configuration, group_locator: &str, role_id: &str, scope: &str) -> Result<models::RoleAssignment, Error<GetGroupRoleAtScopeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_locator = group_locator;
    let p_path_role_id = role_id;
    let p_path_scope = scope;

    let uri_str = format!("{}/app/rest/userGroups/{groupLocator}/roles/{roleId}/{scope}", configuration.base_path, groupLocator=crate::apis::urlencode(p_path_group_locator), roleId=crate::apis::urlencode(p_path_role_id), scope=crate::apis::urlencode(p_path_scope));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RoleAssignment`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RoleAssignment`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetGroupRoleAtScopeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_group_roles(configuration: &configuration::Configuration, group_locator: &str) -> Result<models::RoleAssignments, Error<GetGroupRolesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_locator = group_locator;

    let uri_str = format!("{}/app/rest/userGroups/{groupLocator}/roles", configuration.base_path, groupLocator=crate::apis::urlencode(p_path_group_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RoleAssignments`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RoleAssignments`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetGroupRolesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_user_group_of_group(configuration: &configuration::Configuration, group_locator: &str, fields: Option<&str>) -> Result<models::Group, Error<GetUserGroupOfGroupError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_locator = group_locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/userGroups/{groupLocator}", configuration.base_path, groupLocator=crate::apis::urlencode(p_path_group_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Group`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Group`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetUserGroupOfGroupError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn remove_group_property(configuration: &configuration::Configuration, group_locator: &str, name: &str) -> Result<(), Error<RemoveGroupPropertyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_locator = group_locator;
    let p_path_name = name;

    let uri_str = format!("{}/app/rest/userGroups/{groupLocator}/properties/{name}", configuration.base_path, groupLocator=crate::apis::urlencode(p_path_group_locator), name=crate::apis::urlencode(p_path_name));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RemoveGroupPropertyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn remove_role_at_scope_from_group(configuration: &configuration::Configuration, group_locator: &str, role_id: &str, scope: &str) -> Result<(), Error<RemoveRoleAtScopeFromGroupError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_locator = group_locator;
    let p_path_role_id = role_id;
    let p_path_scope = scope;

    let uri_str = format!("{}/app/rest/userGroups/{groupLocator}/roles/{roleId}/{scope}", configuration.base_path, groupLocator=crate::apis::urlencode(p_path_group_locator), roleId=crate::apis::urlencode(p_path_role_id), scope=crate::apis::urlencode(p_path_scope));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RemoveRoleAtScopeFromGroupError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn set_group_parent_groups(configuration: &configuration::Configuration, group_locator: &str, fields: Option<&str>, body: Option<models::Groups>) -> Result<models::Groups, Error<SetGroupParentGroupsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_locator = group_locator;
    let p_query_fields = fields;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/userGroups/{groupLocator}/parent-groups", configuration.base_path, groupLocator=crate::apis::urlencode(p_path_group_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Groups`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Groups`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SetGroupParentGroupsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn set_group_property(configuration: &configuration::Configuration, group_locator: &str, name: &str, body: Option<&str>) -> Result<String, Error<SetGroupPropertyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_locator = group_locator;
    let p_path_name = name;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/userGroups/{groupLocator}/properties/{name}", configuration.base_path, groupLocator=crate::apis::urlencode(p_path_group_locator), name=crate::apis::urlencode(p_path_name));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SetGroupPropertyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn set_group_roles(configuration: &configuration::Configuration, group_locator: &str, body: Option<models::RoleAssignments>) -> Result<models::RoleAssignments, Error<SetGroupRolesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_group_locator = group_locator;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/userGroups/{groupLocator}/roles", configuration.base_path, groupLocator=crate::apis::urlencode(p_path_group_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RoleAssignments`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RoleAssignments`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SetGroupRolesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

