/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`add_versioned_settings_tokens`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddVersionedSettingsTokensError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`check_for_versioned_settings_changes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CheckForVersionedSettingsChangesError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`commit_current_settings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CommitCurrentSettingsError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_versioned_settings_config_parameter`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteVersionedSettingsConfigParameterError {
    DefaultResponse(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_versioned_settings_tokens`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteVersionedSettingsTokensError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_versioned_settings_config`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVersionedSettingsConfigError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_versioned_settings_config_parameter`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVersionedSettingsConfigParameterError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_versioned_settings_context_parameters`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVersionedSettingsContextParametersError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_versioned_settings_projects_to_load`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVersionedSettingsProjectsToLoadError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_versioned_settings_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVersionedSettingsStatusError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_versioned_settings_tokens`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVersionedSettingsTokensError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`load_settings_from_vcs`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LoadSettingsFromVcsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_versioned_settings_config`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetVersionedSettingsConfigError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_versioned_settings_config_parameter`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetVersionedSettingsConfigParameterError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_versioned_settings_context_parameters`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetVersionedSettingsContextParametersError {
    UnknownValue(serde_json::Value),
}


pub async fn add_versioned_settings_tokens(configuration: &configuration::Configuration, locator: &str, body: Option<models::VersionedSettingsTokens>) -> Result<models::VersionedSettingsTokens, Error<AddVersionedSettingsTokensError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_locator = locator;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/projects/{locator}/versionedSettings/tokens", configuration.base_path, locator=crate::apis::urlencode(p_path_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VersionedSettingsTokens`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::VersionedSettingsTokens`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AddVersionedSettingsTokensError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn check_for_versioned_settings_changes(configuration: &configuration::Configuration, locator: &str) -> Result<(), Error<CheckForVersionedSettingsChangesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_locator = locator;

    let uri_str = format!("{}/app/rest/projects/{locator}/versionedSettings/checkForChanges", configuration.base_path, locator=crate::apis::urlencode(p_path_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<CheckForVersionedSettingsChangesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn commit_current_settings(configuration: &configuration::Configuration, locator: &str) -> Result<(), Error<CommitCurrentSettingsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_locator = locator;

    let uri_str = format!("{}/app/rest/projects/{locator}/versionedSettings/commitCurrentSettings", configuration.base_path, locator=crate::apis::urlencode(p_path_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<CommitCurrentSettingsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delete_versioned_settings_config_parameter(configuration: &configuration::Configuration, locator: &str, name: &str) -> Result<(), Error<DeleteVersionedSettingsConfigParameterError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_locator = locator;
    let p_path_name = name;

    let uri_str = format!("{}/app/rest/projects/{locator}/versionedSettings/config/parameters/{name}", configuration.base_path, locator=crate::apis::urlencode(p_path_locator), name=crate::apis::urlencode(p_path_name));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteVersionedSettingsConfigParameterError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delete_versioned_settings_tokens(configuration: &configuration::Configuration, locator: &str, body: Option<models::VersionedSettingsTokens>) -> Result<models::VersionedSettingsTokens, Error<DeleteVersionedSettingsTokensError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_locator = locator;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/projects/{locator}/versionedSettings/tokens", configuration.base_path, locator=crate::apis::urlencode(p_path_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VersionedSettingsTokens`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::VersionedSettingsTokens`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteVersionedSettingsTokensError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_versioned_settings_config(configuration: &configuration::Configuration, locator: &str, fields: Option<&str>) -> Result<models::VersionedSettingsConfig, Error<GetVersionedSettingsConfigError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_locator = locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/projects/{locator}/versionedSettings/config", configuration.base_path, locator=crate::apis::urlencode(p_path_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VersionedSettingsConfig`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::VersionedSettingsConfig`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetVersionedSettingsConfigError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_versioned_settings_config_parameter(configuration: &configuration::Configuration, locator: &str, name: &str) -> Result<String, Error<GetVersionedSettingsConfigParameterError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_locator = locator;
    let p_path_name = name;

    let uri_str = format!("{}/app/rest/projects/{locator}/versionedSettings/config/parameters/{name}", configuration.base_path, locator=crate::apis::urlencode(p_path_locator), name=crate::apis::urlencode(p_path_name));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetVersionedSettingsConfigParameterError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_versioned_settings_context_parameters(configuration: &configuration::Configuration, locator: &str) -> Result<models::VersionedSettingsContextParameters, Error<GetVersionedSettingsContextParametersError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_locator = locator;

    let uri_str = format!("{}/app/rest/projects/{locator}/versionedSettings/contextParameters", configuration.base_path, locator=crate::apis::urlencode(p_path_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VersionedSettingsContextParameters`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::VersionedSettingsContextParameters`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetVersionedSettingsContextParametersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_versioned_settings_projects_to_load(configuration: &configuration::Configuration, locator: &str, fields: Option<&str>) -> Result<models::Projects, Error<GetVersionedSettingsProjectsToLoadError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_locator = locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/projects/{locator}/versionedSettings/affectedProjects", configuration.base_path, locator=crate::apis::urlencode(p_path_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Projects`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Projects`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetVersionedSettingsProjectsToLoadError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_versioned_settings_status(configuration: &configuration::Configuration, locator: &str, fields: Option<&str>) -> Result<models::VersionedSettingsStatus, Error<GetVersionedSettingsStatusError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_locator = locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/projects/{locator}/versionedSettings/status", configuration.base_path, locator=crate::apis::urlencode(p_path_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VersionedSettingsStatus`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::VersionedSettingsStatus`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetVersionedSettingsStatusError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_versioned_settings_tokens(configuration: &configuration::Configuration, locator: &str, status: Option<&str>) -> Result<models::VersionedSettingsTokens, Error<GetVersionedSettingsTokensError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_locator = locator;
    let p_query_status = status;

    let uri_str = format!("{}/app/rest/projects/{locator}/versionedSettings/tokens", configuration.base_path, locator=crate::apis::urlencode(p_path_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_status {
        req_builder = req_builder.query(&[("status", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VersionedSettingsTokens`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::VersionedSettingsTokens`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetVersionedSettingsTokensError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn load_settings_from_vcs(configuration: &configuration::Configuration, locator: &str, fields: Option<&str>) -> Result<models::Projects, Error<LoadSettingsFromVcsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_locator = locator;
    let p_query_fields = fields;

    let uri_str = format!("{}/app/rest/projects/{locator}/versionedSettings/loadSettings", configuration.base_path, locator=crate::apis::urlencode(p_path_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Projects`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Projects`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LoadSettingsFromVcsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn set_versioned_settings_config(configuration: &configuration::Configuration, locator: &str, fields: Option<&str>, body: Option<models::VersionedSettingsConfig>) -> Result<models::VersionedSettingsConfig, Error<SetVersionedSettingsConfigError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_locator = locator;
    let p_query_fields = fields;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/projects/{locator}/versionedSettings/config", configuration.base_path, locator=crate::apis::urlencode(p_path_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref param_value) = p_query_fields {
        req_builder = req_builder.query(&[("fields", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VersionedSettingsConfig`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::VersionedSettingsConfig`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SetVersionedSettingsConfigError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn set_versioned_settings_config_parameter(configuration: &configuration::Configuration, locator: &str, name: &str, body: Option<&str>) -> Result<String, Error<SetVersionedSettingsConfigParameterError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_locator = locator;
    let p_path_name = name;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/projects/{locator}/versionedSettings/config/parameters/{name}", configuration.base_path, locator=crate::apis::urlencode(p_path_locator), name=crate::apis::urlencode(p_path_name));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Ok(content),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SetVersionedSettingsConfigParameterError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn set_versioned_settings_context_parameters(configuration: &configuration::Configuration, locator: &str, body: Option<models::VersionedSettingsContextParameters>) -> Result<models::VersionedSettingsContextParameters, Error<SetVersionedSettingsContextParametersError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_locator = locator;
    let p_body_body = body;

    let uri_str = format!("{}/app/rest/projects/{locator}/versionedSettings/contextParameters", configuration.base_path, locator=crate::apis::urlencode(p_path_locator));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VersionedSettingsContextParameters`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::VersionedSettingsContextParameters`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SetVersionedSettingsContextParametersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

