/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentTypes : Represents a paginated list of AgentType entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentTypes {
    /// The relative link (without the server URL) used to retrieve this object.
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    /// If the list of returned entities exceeds the request `count` value, TeamCity splits it into multiple batches. This property returns the endpoint that allows you to obtain the next batch.
    #[serde(rename = "nextHref", skip_serializing_if = "Option::is_none")]
    pub next_href: Option<String>,
    /// If the list of returned entities exceeds the request `count` value, TeamCity splits it into multiple batches. This property returns the endpoint that allows you to obtain the previous batch.
    #[serde(rename = "prevHref", skip_serializing_if = "Option::is_none")]
    pub prev_href: Option<String>,
    /// The list of AgentTypes owned by this collection.
    #[serde(rename = "agentType", skip_serializing_if = "Option::is_none")]
    pub agent_type: Option<Vec<models::AgentType>>,
    /// The current number of AgentType objects in this list.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
}

impl AgentTypes {
    /// Represents a paginated list of AgentType entities.
    pub fn new() -> AgentTypes {
        AgentTypes {
            href: None,
            next_href: None,
            prev_href: None,
            agent_type: None,
            count: None,
        }
    }
}

