/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentPoolLocator : Represents a locator string for filtering AgentPool entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentPoolLocator {
    /// Agent pool id.
    #[serde(rename = "$singleValue", skip_serializing_if = "Option::is_none")]
    pub dollar_single_value: Option<i64>,
    /// Pool's associated agents locator.
    #[serde(rename = "agent", skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
    /// For paginated calls, how many entities to return per page.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Agent pool id.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// Agent pool name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Pool's associated projects locator.
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    /// For paginated calls, from which entity to start rendering the page.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i64>,
}

impl AgentPoolLocator {
    /// Represents a locator string for filtering AgentPool entities.
    pub fn new() -> AgentPoolLocator {
        AgentPoolLocator {
            dollar_single_value: None,
            agent: None,
            count: None,
            id: None,
            name: None,
            project: None,
            start: None,
        }
    }
}

