/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentTypeLocator : Represents a locator string for filtering AgentType entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentTypeLocator {
    /// id of the AgentType.
    #[serde(rename = "$singleValue", skip_serializing_if = "Option::is_none")]
    pub dollar_single_value: Option<String>,
    /// AgentType of the given agent.
    #[serde(rename = "agent", skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
    /// For paginated calls, how many entities to return per page.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// id of the AgentType.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// For paginated calls, from which entity to start rendering the page.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i64>,
}

impl AgentTypeLocator {
    /// Represents a locator string for filtering AgentType entities.
    pub fn new() -> AgentTypeLocator {
        AgentTypeLocator {
            dollar_single_value: None,
            agent: None,
            count: None,
            id: None,
            start: None,
        }
    }
}

