/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Agent : Represents a known agent instance.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Agent {
    /// An integer value that is the unique agent identificator.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The public agent name. Cloud agent names are typically formed by appending the unique instance name to the parent cloud profile name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Returns the unique ID of the agent category. Local standalone have unique type IDs whereas cloud agents spawned from the same cloud image have the same type ID.
    #[serde(rename = "typeId", skip_serializing_if = "Option::is_none")]
    pub type_id: Option<i32>,
    /// Returns *true* if the agent is connected to the TeamCity server; otherwise, *false*. Connected agents are those that can communicate with the TeamCity server.
    #[serde(rename = "connected", skip_serializing_if = "Option::is_none")]
    pub connected: Option<bool>,
    /// Returns *true* if the agent is enabled; otherwise, *false*. Enabled agents are those that are ready to process new bulds.  Send `PUT` requests to the [`/app/rest/agents/{agentLocator}/enabledInfo`](https://www.jetbrains.com/help/teamcity/rest/agentapi.html#setEnabledInfo) endpoint to manually enable or disable agents.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Returns *true* if the agent is authorized on the server; otherwise, *false*. Authorized agents are those that are granted permission to execute building tasks on this TeamCity server.  Send `PUT` requests to the [`/app/rest/agents/{agentLocator}/authorizedInfo`](https://www.jetbrains.com/help/teamcity/rest/agentapi.html#setAuthorizedInfo) endpoint to manually authorize or unauthorize agents.
    #[serde(rename = "authorized", skip_serializing_if = "Option::is_none")]
    pub authorized: Option<bool>,
    /// Returns *true* if both `outdated` and `pluginsOutdated` properties return *false*; *false* if any of these properties returns *true*.
    #[serde(rename = "uptodate", skip_serializing_if = "Option::is_none")]
    pub uptodate: Option<bool>,
    /// Returns *true* for outdated agents that require an update; *false* for agents that are up to date. Agents typically update their software automatically and do not require any actions from your side.
    #[serde(rename = "outdated", skip_serializing_if = "Option::is_none")]
    pub outdated: Option<bool>,
    /// Returns *false* if all plugins installed on this agent are of the latest version; *true* if some of plugins are outdated. Plugins installed from the JetBrains Marketplace are typically updated automatically.
    #[serde(rename = "pluginsOutdated", skip_serializing_if = "Option::is_none")]
    pub plugins_outdated: Option<bool>,
    /// Returns *true* the Java version installed on the agent machine is outdated; otherwise, *false*.
    #[serde(rename = "javaOutdated", skip_serializing_if = "Option::is_none")]
    pub java_outdated: Option<bool>,
    /// The IP address of the agent machine.
    #[serde(rename = "ip", skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
    /// Returns the agent-server communication protocol type:  * *unidirectional* — the default one-way communication protocol. Unidirectional agents establish an HTTP(S) connection to the TeamCity server, and periodically poll it for server commands. * *bidirectional* — [no longer supported](https://www.jetbrains.com/help/teamcity/upgrade-notes.html#Canceled+bidirectional+agent-server+communication+protocol) in TeamCity 2021.2 and newer.
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<Protocol>,
    /// The actual version of the agent software or 'unknown' if the agent is disconnected. If this version differs from the version expected by the server (the `currentAgentVersion` property), the agent is considered outdated.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// The version of the agent software that is expected by the current TeamCity server. Matches the build number of this server (can be obtained from the `/app/rest/server/build` endpoint).
    #[serde(rename = "currentAgentVersion", skip_serializing_if = "Option::is_none")]
    pub current_agent_version: Option<String>,
    /// The timestamp of the last comminication between this agent and the TeamCity server.  To get the last time this agent performed an activity different from periodic server polling (for example, ran a build), use the `idleSinceTime` property instead.
    #[serde(rename = "lastActivityTime", skip_serializing_if = "Option::is_none")]
    pub last_activity_time: Option<String>,
    /// The timestamp of the last meaningful agent activity (for example, running a build). For agents that never ran a build after they were authorized by the server, this timestamp is typically equal to the `registrationTimestamp` property value.
    #[serde(rename = "idleSinceTime", skip_serializing_if = "Option::is_none")]
    pub idle_since_time: Option<String>,
    /// The summary that explains why this agent was disconnected. Returns `null` for connected agents.
    #[serde(rename = "disconnectionComment", skip_serializing_if = "Option::is_none")]
    pub disconnection_comment: Option<String>,
    /// The timestamp of the first successful agent authorization on this server.
    #[serde(rename = "registrationTimestamp", skip_serializing_if = "Option::is_none")]
    pub registration_timestamp: Option<String>,
    /// The name of the agent machine host.
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    /// An integer value that is the [benchmarking score](https://www.jetbrains.com/help/teamcity/viewing-build-agent-details.html#Agent+Summary) of the agent machine's CPU.
    #[serde(rename = "cpuRank", skip_serializing_if = "Option::is_none")]
    pub cpu_rank: Option<i32>,
    /// The port used by the TeamCity server to connect to the agent.
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
    /// Returns the shortened (without the server URL) link to the current agent. To obtain the full URL, use the *webUrl* property instead.
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    /// Returns the full web link to access this agent. To get a shortened link without the server URL, read the *href* property instead.
    #[serde(rename = "webUrl", skip_serializing_if = "Option::is_none")]
    pub web_url: Option<String>,
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<Box<models::Build>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<models::Links>>,
    #[serde(rename = "enabledInfo", skip_serializing_if = "Option::is_none")]
    pub enabled_info: Option<Box<models::EnabledInfo>>,
    #[serde(rename = "authorizedInfo", skip_serializing_if = "Option::is_none")]
    pub authorized_info: Option<Box<models::AuthorizedInfo>>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<models::Properties>>,
    #[serde(rename = "cloudInstance", skip_serializing_if = "Option::is_none")]
    pub cloud_instance: Option<Box<models::CloudInstance>>,
    #[serde(rename = "cloudImage", skip_serializing_if = "Option::is_none")]
    pub cloud_image: Option<Box<models::CloudImage>>,
    #[serde(rename = "environment", skip_serializing_if = "Option::is_none")]
    pub environment: Option<Box<models::Environment>>,
    #[serde(rename = "pool", skip_serializing_if = "Option::is_none")]
    pub pool: Option<Box<models::AgentPool>>,
    #[serde(rename = "compatibilityPolicy", skip_serializing_if = "Option::is_none")]
    pub compatibility_policy: Option<Box<models::CompatibilityPolicy>>,
    #[serde(rename = "compatibleBuildTypes", skip_serializing_if = "Option::is_none")]
    pub compatible_build_types: Option<Box<models::BuildTypes>>,
    #[serde(rename = "incompatibleBuildTypes", skip_serializing_if = "Option::is_none")]
    pub incompatible_build_types: Option<Box<models::Compatibilities>>,
    #[serde(rename = "builds", skip_serializing_if = "Option::is_none")]
    pub builds: Option<Box<models::Builds>>,
    /// Returns *true* if the agent was removed after a long period of inactivity; otherwise, *false*.
    #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
    pub removed: Option<bool>,
    #[serde(rename = "locator", skip_serializing_if = "Option::is_none")]
    pub locator: Option<String>,
}

impl Agent {
    /// Represents a known agent instance.
    pub fn new() -> Agent {
        Agent {
            id: None,
            name: None,
            type_id: None,
            connected: None,
            enabled: None,
            authorized: None,
            uptodate: None,
            outdated: None,
            plugins_outdated: None,
            java_outdated: None,
            ip: None,
            protocol: None,
            version: None,
            current_agent_version: None,
            last_activity_time: None,
            idle_since_time: None,
            disconnection_comment: None,
            registration_timestamp: None,
            host: None,
            cpu_rank: None,
            port: None,
            href: None,
            web_url: None,
            build: None,
            links: None,
            enabled_info: None,
            authorized_info: None,
            properties: None,
            cloud_instance: None,
            cloud_image: None,
            environment: None,
            pool: None,
            compatibility_policy: None,
            compatible_build_types: None,
            incompatible_build_types: None,
            builds: None,
            removed: None,
            locator: None,
        }
    }
}
/// Returns the agent-server communication protocol type:  * *unidirectional* — the default one-way communication protocol. Unidirectional agents establish an HTTP(S) connection to the TeamCity server, and periodically poll it for server commands. * *bidirectional* — [no longer supported](https://www.jetbrains.com/help/teamcity/upgrade-notes.html#Canceled+bidirectional+agent-server+communication+protocol) in TeamCity 2021.2 and newer.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Protocol {
    #[serde(rename = "unidirectional")]
    Unidirectional,
    #[serde(rename = "bidirectional")]
    Bidirectional,
}

impl Default for Protocol {
    fn default() -> Protocol {
        Self::Unidirectional
    }
}

