/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApprovableBuild : A build that cannot start until explicitly approved by designated team members. See the [Build approval](https://www.jetbrains.com/help/teamcity/build-approval.html) build feature and [Untrusted Builds](https://www.jetbrains.com/help/teamcity/untrusted-builds.html) project settings for more information. Send a `POST` request to the `/app/rest/buildQueue/{buildLocator}/approve` endpoint to manually approve a build.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApprovableBuild {
    /// The ID of a build that requires manual approval.
    #[serde(rename = "buildId", skip_serializing_if = "Option::is_none")]
    pub build_id: Option<String>,
    /// The ID of a build configuration that spawned this approvable build.
    #[serde(rename = "buildTypeId", skip_serializing_if = "Option::is_none")]
    pub build_type_id: Option<String>,
    /// The name of a build configuration that spawned this approvable build.
    #[serde(rename = "buildTypeName", skip_serializing_if = "Option::is_none")]
    pub build_type_name: Option<String>,
}

impl ApprovableBuild {
    /// A build that cannot start until explicitly approved by designated team members. See the [Build approval](https://www.jetbrains.com/help/teamcity/build-approval.html) build feature and [Untrusted Builds](https://www.jetbrains.com/help/teamcity/untrusted-builds.html) project settings for more information. Send a `POST` request to the `/app/rest/buildQueue/{buildLocator}/approve` endpoint to manually approve a build.
    pub fn new() -> ApprovableBuild {
        ApprovableBuild {
            build_id: None,
            build_type_id: None,
            build_type_name: None,
        }
    }
}

