/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ArtifactDependencies : Represents a list of ArtifactDependency entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArtifactDependencies {
    /// The number of `artifact_dependency` objects in this collection.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The list of `artifact_dependency` objects owned by this collection.
    #[serde(rename = "artifact-dependency", skip_serializing_if = "Option::is_none")]
    pub artifact_dependency: Option<Vec<models::ArtifactDependency>>,
    #[serde(rename = "replace", skip_serializing_if = "Option::is_none")]
    pub replace: Option<String>,
}

impl ArtifactDependencies {
    /// Represents a list of ArtifactDependency entities.
    pub fn new() -> ArtifactDependencies {
        ArtifactDependencies {
            count: None,
            artifact_dependency: None,
            replace: None,
        }
    }
}

