/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthModules {
    #[serde(rename = "module", skip_serializing_if = "Option::is_none")]
    pub module: Option<Vec<models::AuthModule>>,
}

impl AuthModules {
    pub fn new() -> AuthModules {
        AuthModules {
            module: None,
        }
    }
}

