/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use std::default::Default as StdDefault;

/// BranchLocator : Represents a locator string for filtering Branch entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BranchLocator {
    /// Branch name.
    #[serde(rename = "$singleValue", skip_serializing_if = "Option::is_none")]
    pub dollar_single_value: Option<String>,
    /// Build locator.
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<String>,
    /// Build type locator.
    #[serde(rename = "buildType", skip_serializing_if = "Option::is_none")]
    pub build_type: Option<String>,
    /// Include branches from dependencies.
    #[serde(
        rename = "changesFromDependencies",
        skip_serializing_if = "Option::is_none"
    )]
    pub changes_from_dependencies: Option<ChangesFromDependencies>,
    /// For paginated calls, how many entities to return per page.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Is default branch.
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<Default>,
    /// Branch name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Branch retrieval policy.
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<Policy>,
    /// For paginated calls, from which entity to start rendering the page.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i64>,
    /// Branch is unspecified if for some reason TeamCity failed to find appropriate branch name for the build.
    #[serde(rename = "unspecified", skip_serializing_if = "Option::is_none")]
    pub unspecified: Option<Unspecified>,
}

impl BranchLocator {
    /// Represents a locator string for filtering Branch entities.
    pub fn new() -> BranchLocator {
        BranchLocator {
            dollar_single_value: None,
            build: None,
            build_type: None,
            changes_from_dependencies: None,
            count: None,
            default: None,
            name: None,
            policy: None,
            start: None,
            unspecified: None,
        }
    }
}
/// Include branches from dependencies.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChangesFromDependencies {
    #[serde(rename = "true")]
    True,
    #[serde(rename = "false")]
    False,
    #[serde(rename = "any")]
    Any,
}

impl StdDefault for ChangesFromDependencies {
    fn default() -> ChangesFromDependencies {
        Self::True
    }
}
/// Is default branch.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Default {
    #[serde(rename = "true")]
    True,
    #[serde(rename = "false")]
    False,
    #[serde(rename = "any")]
    Any,
}

impl StdDefault for Default {
    fn default() -> Default {
        Self::True
    }
}
/// Branch retrieval policy.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Policy {
    #[serde(rename = "vcs_branches")]
    VcsBranches,
    #[serde(rename = "active_vcs_branches")]
    ActiveVcsBranches,
    #[serde(rename = "history_branches")]
    HistoryBranches,
    #[serde(rename = "active_history_branches")]
    ActiveHistoryBranches,
    #[serde(rename = "active_history_and_active_vcs_branches")]
    ActiveHistoryAndActiveVcsBranches,
    #[serde(rename = "all_branches")]
    AllBranches,
}

impl StdDefault for Policy {
    fn default() -> Policy {
        Self::VcsBranches
    }
}
/// Branch is unspecified if for some reason TeamCity failed to find appropriate branch name for the build.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Unspecified {
    #[serde(rename = "true")]
    True,
    #[serde(rename = "false")]
    False,
    #[serde(rename = "any")]
    Any,
}

impl StdDefault for Unspecified {
    fn default() -> Unspecified {
        Self::True
    }
}
