/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BranchVersion : An object that describes the actual state of a repository branch. Inherits the majority of its properties from the base Branch class.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BranchVersion {
    /// The full revision SHA. Points to the latest commit in this branch.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// Returns **true** if the branch belongs to the automatically created 'My Branches' group; otherwise, **false**. Branch grouping allows TeamCity to automatically categorize branches based on current TeamCity user commits.
    #[serde(rename = "groupFlag", skip_serializing_if = "Option::is_none")]
    pub group_flag: Option<bool>,
    #[serde(rename = "builds", skip_serializing_if = "Option::is_none")]
    pub builds: Option<Box<models::Builds>>,
    /// Returns the date and time of the last branch activity (the last TeamCity build or the latest VCS commit).
    #[serde(rename = "lastActivity", skip_serializing_if = "Option::is_none")]
    pub last_activity: Option<String>,
    /// Returns **true** for unspecified branches; otherwise, **false**. A branch is labeled as unspecified when TeamCity fails to find a branch for this build. Such branches have a predefined '<unspecified>' name.
    #[serde(rename = "unspecified", skip_serializing_if = "Option::is_none")]
    pub unspecified: Option<bool>,
    /// A public branch name displayed in TeamCity UI. To get a full VCS name instead (for example, 'refs/heads/main'), read the *vcsBranchName* property of a nested Revision entity.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Returns **true** if this branch is the default branch of this build configuration; otherwise, **false**. When obtaining builds of the specific BuildType, add the *branch(default:any)* locator to get builds from all existing branches.
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<bool>,
    /// Returns **true** for active branches and **false** for inactive ones. A branch is considered inactive if it had neither new TeamCity builds in the last 24 hours, nor recent VCS repository changes in the last 7 days. Learn more: [Active branches](https://www.jetbrains.com/help/teamcity/working-with-feature-branches.html#Active+Branches).
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// An internal branch name. Returns `<default>` for default branches, and real branch names for other (non-default) branches.
    #[serde(rename = "internalName", skip_serializing_if = "Option::is_none")]
    pub internal_name: Option<String>,
}

impl BranchVersion {
    /// An object that describes the actual state of a repository branch. Inherits the majority of its properties from the base Branch class.
    pub fn new() -> BranchVersion {
        BranchVersion {
            version: None,
            group_flag: None,
            builds: None,
            last_activity: None,
            unspecified: None,
            name: None,
            default: None,
            active: None,
            internal_name: None,
        }
    }
}

