/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Branches : Represents a list of Branch entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Branches {
    /// The current number of Branch objects in this list.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The relative link (without the server URL) used to retrieve this object.
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    /// The list of branches owned by this collection that satisfy the given locator.
    #[serde(rename = "branch", skip_serializing_if = "Option::is_none")]
    pub branch: Option<Vec<models::Branch>>,
}

impl Branches {
    /// Represents a list of Branch entities.
    pub fn new() -> Branches {
        Branches {
            count: None,
            href: None,
            branch: None,
        }
    }
}

