/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BuildChanges : Represents a list of BuildChange entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildChanges {
    /// The current number of BuildChange objects in this list.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The list of BuildChange objects owned by this collection.
    #[serde(rename = "buildChange", skip_serializing_if = "Option::is_none")]
    pub build_change: Option<Vec<models::BuildChange>>,
}

impl BuildChanges {
    /// Represents a list of BuildChange entities.
    pub fn new() -> BuildChanges {
        BuildChanges {
            count: None,
            build_change: None,
        }
    }
}

