/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BuildChange : If builds of a consumer build configuration import build artifacts from builds of a source build configuration, BuildChange objects allow you to identify whether consecutive consumer builds obtain artifacts from different source builds or the same one.   See [Build.ArtifactDependencyChanges](https://www.jetbrains.com/help/teamcity/rest/build.html#artifactDependencyChanges) for more information.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildChange {
    #[serde(rename = "nextBuild", skip_serializing_if = "Option::is_none")]
    pub next_build: Option<Box<models::Build>>,
    #[serde(rename = "prevBuild", skip_serializing_if = "Option::is_none")]
    pub prev_build: Option<Box<models::Build>>,
}

impl BuildChange {
    /// If builds of a consumer build configuration import build artifacts from builds of a source build configuration, BuildChange objects allow you to identify whether consecutive consumer builds obtain artifacts from different source builds or the same one.   See [Build.ArtifactDependencyChanges](https://www.jetbrains.com/help/teamcity/rest/build.html#artifactDependencyChanges) for more information.
    pub fn new() -> BuildChange {
        BuildChange {
            next_build: None,
            prev_build: None,
        }
    }
}

