/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BuildStatusUpdate : Send instances of this class to the `/app/rest/builds/<locator>/status` endpoint to change the status of a build to either 'SUCCESS' or 'FAILURE'. This replicates the *Mark as failed...* and *Mark as successful...* operations available from the 'Actions' menu on the build results page in TeamCity UI.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildStatusUpdate {
    /// Set to either 'FAILURE' or 'SUCCESS'.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Your custom note that explains why the build status was manually changed.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
}

impl BuildStatusUpdate {
    /// Send instances of this class to the `/app/rest/builds/<locator>/status` endpoint to change the status of a build to either 'SUCCESS' or 'FAILURE'. This replicates the *Mark as failed...* and *Mark as successful...* operations available from the 'Actions' menu on the build results page in TeamCity UI.
    pub fn new() -> BuildStatusUpdate {
        BuildStatusUpdate {
            status: None,
            comment: None,
        }
    }
}

