/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BuildQueueLocator : Represents a locator string for filtering Build entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildQueueLocator {
    /// Agent locator.
    #[serde(rename = "agent", skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
    /// Build type locator.
    #[serde(rename = "buildType", skip_serializing_if = "Option::is_none")]
    pub build_type: Option<String>,
    /// For paginated calls, how many entities to return per page.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// Entity ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Supply multiple locators and return a union of the results.
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<String>,
    /// Is personal.
    #[serde(rename = "personal", skip_serializing_if = "Option::is_none")]
    pub personal: Option<bool>,
    /// Agent pool locator.
    #[serde(rename = "pool", skip_serializing_if = "Option::is_none")]
    pub pool: Option<String>,
    /// Project locator.
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    /// For paginated calls, from which entity to start rendering the page.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i32>,
    /// Deprecated.
    #[serde(rename = "taskId", skip_serializing_if = "Option::is_none")]
    pub task_id: Option<String>,
    /// User locator.
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
}

impl BuildQueueLocator {
    /// Represents a locator string for filtering Build entities.
    pub fn new() -> BuildQueueLocator {
        BuildQueueLocator {
            agent: None,
            build_type: None,
            count: None,
            id: None,
            item: None,
            personal: None,
            pool: None,
            project: None,
            start: None,
            task_id: None,
            user: None,
        }
    }
}

