/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BuildsWithReason : Stores builds that cannot be started without an explicit approval, along with reasons why these builds require an approval.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildsWithReason {
    /// The list of builds that cannot start without an approval.
    #[serde(rename = "builds", skip_serializing_if = "Option::is_none")]
    pub builds: Option<Vec<models::ApprovableBuild>>,
    #[serde(rename = "approvalReason", skip_serializing_if = "Option::is_none")]
    pub approval_reason: Option<Box<models::ApprovableBuild>>,
}

impl BuildsWithReason {
    /// Stores builds that cannot be started without an explicit approval, along with reasons why these builds require an approval.
    pub fn new() -> BuildsWithReason {
        BuildsWithReason {
            builds: None,
            approval_reason: None,
        }
    }
}

