/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BuildExecutor : Represents an executor of a build.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildExecutor {
    /// The name of an external executor that processed this build.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl BuildExecutor {
    /// Represents an executor of a build.
    pub fn new() -> BuildExecutor {
        BuildExecutor {
            name: None,
        }
    }
}

