/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BuildTypeLocator : Represents a locator string for filtering BuildType entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildTypeLocator {
    /// Project (direct or indirect parent) locator.
    #[serde(rename = "affectedProject", skip_serializing_if = "Option::is_none")]
    pub affected_project: Option<String>,
    /// Build locator.
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<String>,
    /// For paginated calls, how many entities to return per page.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<String>,
    /// Supply multiple locators and return a union of the results.
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Is paused.
    #[serde(rename = "paused", skip_serializing_if = "Option::is_none")]
    pub paused: Option<bool>,
    /// Project (direct parent) locator.
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    /// For paginated calls, from which entity to start rendering the page.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i32>,
    /// Base template locator.
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<String>,
    /// Is a template.
    #[serde(rename = "templateFlag", skip_serializing_if = "Option::is_none")]
    pub template_flag: Option<bool>,
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    /// VCS root locator.
    #[serde(rename = "vcsRoot", skip_serializing_if = "Option::is_none")]
    pub vcs_root: Option<String>,
    /// VCS root instance locator.
    #[serde(rename = "vcsRootInstance", skip_serializing_if = "Option::is_none")]
    pub vcs_root_instance: Option<String>,
}

impl BuildTypeLocator {
    /// Represents a locator string for filtering BuildType entities.
    pub fn new() -> BuildTypeLocator {
        BuildTypeLocator {
            affected_project: None,
            build: None,
            count: None,
            id: None,
            internal_id: None,
            item: None,
            name: None,
            paused: None,
            project: None,
            start: None,
            template: None,
            template_flag: None,
            uuid: None,
            vcs_root: None,
            vcs_root_instance: None,
        }
    }
}

