/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BuildType : A build configuration owned by a TeamCity project, or a template created from this configuration. Spawns builds to execute configured build steps.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildType {
    /// The build configuration ID. Typically consists of a trunkated project and configuration names in the ProjectName_ConfigurationName format.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The automatically generated build configuration ID. This is the internal property and is not intented to be used.
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<String>,
    /// The public build configuration name displayed in TeamCity UI.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Returns *true* if the current BuildType entity is a build configuration template; *false* if this is a regular build configuration. Inspect the `templates` field to view all templates attached to the target configuration.
    #[serde(rename = "templateFlag", skip_serializing_if = "Option::is_none")]
    pub template_flag: Option<bool>,
    /// The build configuration type:  * *regular* — a regular build configuration. * *composite* — a composite configuration that aggregates results of multiple upstream build chain configurations. * *deployment* — a deployment build configuration.  See [Changing build configuration type](https://www.jetbrains.com/help/teamcity/changing-build-configuration-type.html) for more information.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    /// Returns *true* if a configuration is paused and cannot start new builds automatically upon build trigger requests; otherwise, *false*. To pause or unpause a configuration, use the configuration's Actions menu in TeamCity UI or send a `PUT` request with the required Boolean value to the `/app/rest/buildTypes/_build_type_locator_/paused` endpoint.
    #[serde(rename = "paused", skip_serializing_if = "Option::is_none")]
    pub paused: Option<bool>,
    /// An internally used universally unique identifier.
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    /// The custom build configuration description, or *null* if not set.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The public name of a parent TeamCity project.
    #[serde(rename = "projectName", skip_serializing_if = "Option::is_none")]
    pub project_name: Option<String>,
    /// The ID of a parent TeamCity project that owns this build configuration.
    #[serde(rename = "projectId", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    /// The automatically generated ID of a parent project. This is the internal property and is not intented to be used.
    #[serde(rename = "projectInternalId", skip_serializing_if = "Option::is_none")]
    pub project_internal_id: Option<String>,
    /// The short link (without the address of a TeamCity server) to this build configuration.
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    /// The regular URL for this build configuration or template.
    #[serde(rename = "webUrl", skip_serializing_if = "Option::is_none")]
    pub web_url: Option<String>,
    /// Returns *null* for build configurations, *true* for configuration templates inherited from other templates, and *false* for regular templates extracted from build configurations. You can only create templates inherited from other base templates in Kotlin.
    #[serde(rename = "inherited", skip_serializing_if = "Option::is_none")]
    pub inherited: Option<bool>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<models::Links>>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::Project>>,
    #[serde(rename = "templates", skip_serializing_if = "Option::is_none")]
    pub templates: Option<Box<models::BuildTypes>>,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<Box<models::BuildType>>,
    #[serde(rename = "vcs-root-entries", skip_serializing_if = "Option::is_none")]
    pub vcs_root_entries: Option<Box<models::VcsRootEntries>>,
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<Box<models::Properties>>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Box<models::Properties>>,
    #[serde(rename = "output-parameters", skip_serializing_if = "Option::is_none")]
    pub output_parameters: Option<Box<models::Properties>>,
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<Box<models::Steps>>,
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Box<models::Features>>,
    #[serde(rename = "triggers", skip_serializing_if = "Option::is_none")]
    pub triggers: Option<Box<models::Triggers>>,
    #[serde(rename = "snapshot-dependencies", skip_serializing_if = "Option::is_none")]
    pub snapshot_dependencies: Option<Box<models::SnapshotDependencies>>,
    #[serde(rename = "artifact-dependencies", skip_serializing_if = "Option::is_none")]
    pub artifact_dependencies: Option<Box<models::ArtifactDependencies>>,
    #[serde(rename = "agent-requirements", skip_serializing_if = "Option::is_none")]
    pub agent_requirements: Option<Box<models::AgentRequirements>>,
    #[serde(rename = "branches", skip_serializing_if = "Option::is_none")]
    pub branches: Option<Box<models::Branches>>,
    #[serde(rename = "builds", skip_serializing_if = "Option::is_none")]
    pub builds: Option<Box<models::Builds>>,
    #[serde(rename = "investigations", skip_serializing_if = "Option::is_none")]
    pub investigations: Option<Box<models::Investigations>>,
    #[serde(rename = "compatibleAgents", skip_serializing_if = "Option::is_none")]
    pub compatible_agents: Option<Box<models::Agents>>,
    #[serde(rename = "compatibleCloudImages", skip_serializing_if = "Option::is_none")]
    pub compatible_cloud_images: Option<Box<models::CloudImages>>,
    #[serde(rename = "vcsRootInstances", skip_serializing_if = "Option::is_none")]
    pub vcs_root_instances: Option<Box<models::VcsRootInstances>>,
    /// This is the internal property and is not intented to be used.
    #[serde(rename = "externalStatusAllowed", skip_serializing_if = "Option::is_none")]
    pub external_status_allowed: Option<bool>,
    #[serde(rename = "pauseComment", skip_serializing_if = "Option::is_none")]
    pub pause_comment: Option<Box<models::Comment>>,
    #[serde(rename = "locator", skip_serializing_if = "Option::is_none")]
    pub locator: Option<String>,
}

impl BuildType {
    /// A build configuration owned by a TeamCity project, or a template created from this configuration. Spawns builds to execute configured build steps.
    pub fn new() -> BuildType {
        BuildType {
            id: None,
            internal_id: None,
            name: None,
            template_flag: None,
            r#type: None,
            paused: None,
            uuid: None,
            description: None,
            project_name: None,
            project_id: None,
            project_internal_id: None,
            href: None,
            web_url: None,
            inherited: None,
            links: None,
            project: None,
            templates: None,
            template: None,
            vcs_root_entries: None,
            settings: None,
            parameters: None,
            output_parameters: None,
            steps: None,
            features: None,
            triggers: None,
            snapshot_dependencies: None,
            artifact_dependencies: None,
            agent_requirements: None,
            branches: None,
            builds: None,
            investigations: None,
            compatible_agents: None,
            compatible_cloud_images: None,
            vcs_root_instances: None,
            external_status_allowed: None,
            pause_comment: None,
            locator: None,
        }
    }
}
/// The build configuration type:  * *regular* — a regular build configuration. * *composite* — a composite configuration that aggregates results of multiple upstream build chain configurations. * *deployment* — a deployment build configuration.  See [Changing build configuration type](https://www.jetbrains.com/help/teamcity/changing-build-configuration-type.html) for more information.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "regular")]
    Regular,
    #[serde(rename = "composite")]
    Composite,
    #[serde(rename = "deployment")]
    Deployment,
}

impl Default for Type {
    fn default() -> Type {
        Self::Regular
    }
}

