/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChangeStatus : Stores information this change in terms of effects it had on the TeamCity server: the number of failed/cancelled/successful builds, the number of build configurations that have this change in the pending changes list, the number of build problems and failed tests caused by this change, and so on. Fairly expensive to compute.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeStatus {
    /// The number of builds that process this change and are currently running with the 'running and failing' status.
    #[serde(rename = "runningSuccessfullyBuilds", skip_serializing_if = "Option::is_none")]
    pub running_successfully_builds: Option<i32>,
    /// The number of build configurations (build types) that have not yet processed this change and have it in their 'pending changes' list.
    #[serde(rename = "pendingBuildTypes", skip_serializing_if = "Option::is_none")]
    pub pending_build_types: Option<i32>,
    /// Returns how many of `finishedBuilds` finished successfully.
    #[serde(rename = "successfulBuilds", skip_serializing_if = "Option::is_none")]
    pub successful_builds: Option<i32>,
    /// The total number of build problems associated with this change, across all build configurations and their builds.
    #[serde(rename = "totalProblems", skip_serializing_if = "Option::is_none")]
    pub total_problems: Option<i32>,
    /// The total number of new failed tests associated with this change, across all build configurations and their builds.
    #[serde(rename = "newFailedTests", skip_serializing_if = "Option::is_none")]
    pub new_failed_tests: Option<i32>,
    /// The total number of failed tests associated with this change. This number does not inlcude the number of new test failures.
    #[serde(rename = "otherFailedTests", skip_serializing_if = "Option::is_none")]
    pub other_failed_tests: Option<i32>,
    /// The number of currently queued builds whose list of processed changes includes this change.
    #[serde(rename = "queuedBuildsCount", skip_serializing_if = "Option::is_none")]
    pub queued_builds_count: Option<i32>,
    #[serde(rename = "criticalBuilds", skip_serializing_if = "Option::is_none")]
    pub critical_builds: Option<Box<models::Builds>>,
    #[serde(rename = "notCriticalBuilds", skip_serializing_if = "Option::is_none")]
    pub not_critical_builds: Option<Box<models::Builds>>,
    #[serde(rename = "newTestsFailedBuilds", skip_serializing_if = "Option::is_none")]
    pub new_tests_failed_builds: Option<Box<models::Builds>>,
    #[serde(rename = "compilationErrorBuilds", skip_serializing_if = "Option::is_none")]
    pub compilation_error_builds: Option<Box<models::Builds>>,
    /// The number of finished builds that processed this change, regardless of their final status.
    #[serde(rename = "finishedBuilds", skip_serializing_if = "Option::is_none")]
    pub finished_builds: Option<i32>,
    /// The number of currently running builds processing this change, regardless of their current build status.
    #[serde(rename = "runningBuilds", skip_serializing_if = "Option::is_none")]
    pub running_builds: Option<i32>,
    /// Returns how many of `finishedBuilds` failed.
    #[serde(rename = "failedBuilds", skip_serializing_if = "Option::is_none")]
    pub failed_builds: Option<i32>,
    /// Returns how many of `finishedBuilds` were cancelled before they finished.
    #[serde(rename = "cancelledBuilds", skip_serializing_if = "Option::is_none")]
    pub cancelled_builds: Option<i32>,
}

impl ChangeStatus {
    /// Stores information this change in terms of effects it had on the TeamCity server: the number of failed/cancelled/successful builds, the number of build configurations that have this change in the pending changes list, the number of build problems and failed tests caused by this change, and so on. Fairly expensive to compute.
    pub fn new() -> ChangeStatus {
        ChangeStatus {
            running_successfully_builds: None,
            pending_build_types: None,
            successful_builds: None,
            total_problems: None,
            new_failed_tests: None,
            other_failed_tests: None,
            queued_builds_count: None,
            critical_builds: None,
            not_critical_builds: None,
            new_tests_failed_builds: None,
            compilation_error_builds: None,
            finished_builds: None,
            running_builds: None,
            failed_builds: None,
            cancelled_builds: None,
        }
    }
}

