/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChangeLocator : Represents a locator string for filtering Change entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeLocator {
    /// Project (direct or indirect parent) locator.
    #[serde(rename = "affectedProject", skip_serializing_if = "Option::is_none")]
    pub affected_project: Option<String>,
    /// Build locator.
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<String>,
    /// Build type locator.
    #[serde(rename = "buildType", skip_serializing_if = "Option::is_none")]
    pub build_type: Option<String>,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// For paginated calls, how many entities to return per page.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "file", skip_serializing_if = "Option::is_none")]
    pub file: Option<String>,
    /// Entity ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Commit SHA.
    #[serde(rename = "internalVersion", skip_serializing_if = "Option::is_none")]
    pub internal_version: Option<String>,
    /// Supply multiple locators and return a union of the results.
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<String>,
    /// Is pending.
    #[serde(rename = "pending", skip_serializing_if = "Option::is_none")]
    pub pending: Option<bool>,
    /// Project locator.
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    /// Commit SHA since which the changes should be returned.
    #[serde(rename = "sinceChange", skip_serializing_if = "Option::is_none")]
    pub since_change: Option<String>,
    /// For paginated calls, from which entity to start rendering the page.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i32>,
    /// User locator.
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
    /// VCS side username.
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// VCS root locator.
    #[serde(rename = "vcsRoot", skip_serializing_if = "Option::is_none")]
    pub vcs_root: Option<String>,
    /// VCS instance locator.
    #[serde(rename = "vcsRootInstance", skip_serializing_if = "Option::is_none")]
    pub vcs_root_instance: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl ChangeLocator {
    /// Represents a locator string for filtering Change entities.
    pub fn new() -> ChangeLocator {
        ChangeLocator {
            affected_project: None,
            build: None,
            build_type: None,
            comment: None,
            count: None,
            file: None,
            id: None,
            internal_version: None,
            item: None,
            pending: None,
            project: None,
            since_change: None,
            start: None,
            user: None,
            username: None,
            vcs_root: None,
            vcs_root_instance: None,
            version: None,
        }
    }
}

