/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CloudProfile : A cloud profile that stores common cloud agent profiles. These settings are applied to all cloud images owned by this profile.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudProfile {
    /// The internally used cloud profile ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The public cloud profile name displayed in TeamCity UI.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// A shortened name of the cloud provider.
    #[serde(rename = "cloudProviderId", skip_serializing_if = "Option::is_none")]
    pub cloud_provider_id: Option<String>,
    /// The shortened (without the TeamCity server URL) link to this profile.
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::Project>>,
    #[serde(rename = "images", skip_serializing_if = "Option::is_none")]
    pub images: Option<Box<models::CloudImages>>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::CloudError>>,
}

impl CloudProfile {
    /// A cloud profile that stores common cloud agent profiles. These settings are applied to all cloud images owned by this profile.
    pub fn new() -> CloudProfile {
        CloudProfile {
            id: None,
            name: None,
            cloud_provider_id: None,
            href: None,
            project: None,
            images: None,
            error: None,
        }
    }
}

