/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CloudProfileLocator : Represents a locator string for filtering CloudProfile entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudProfileLocator {
    /// Projects where the cloud profiles are accessible
    #[serde(rename = "affectedProject", skip_serializing_if = "Option::is_none")]
    pub affected_project: Option<String>,
    /// Profile cloud provider id.
    #[serde(rename = "cloudProviderId", skip_serializing_if = "Option::is_none")]
    pub cloud_provider_id: Option<String>,
    /// For paginated calls, how many entities to return per page.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Profile id.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Cloud image which belongs to a profile.
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    /// Cloud instance which belongs to a profile.
    #[serde(rename = "instance", skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,
    /// Profile name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Projects defining the cloud profiles.
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(rename = "property", skip_serializing_if = "Option::is_none")]
    pub property: Option<String>,
    /// For paginated calls, from which entity to start rendering the page.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i64>,
}

impl CloudProfileLocator {
    /// Represents a locator string for filtering CloudProfile entities.
    pub fn new() -> CloudProfileLocator {
        CloudProfileLocator {
            affected_project: None,
            cloud_provider_id: None,
            count: None,
            id: None,
            image: None,
            instance: None,
            name: None,
            project: None,
            property: None,
            start: None,
        }
    }
}

