/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CloudInstance : An individual cloud instance spawned from a cloud image.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudInstance {
    /// The internally used read-only ID of this instance.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The name of this instance.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// A String value that specifies the instance current status. Can return the following values: `scheduled to start`, `scheduled to stop`, `starting`, `running`, `restarting`, `stopping`, `stopped`, `unknown`, and `error`.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    /// The time of this instance's initial start.
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    /// The actual instance address.
    #[serde(rename = "networkAddress", skip_serializing_if = "Option::is_none")]
    pub network_address: Option<String>,
    /// The relative (without the TeamCity server URL) link to this instance.
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<Box<models::CloudImage>>,
    #[serde(rename = "agent", skip_serializing_if = "Option::is_none")]
    pub agent: Option<Box<models::Agent>>,
    /// This property is deprecated, use `error` instead.
    #[serde(rename = "errorMessage", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::CloudError>>,
}

impl CloudInstance {
    /// An individual cloud instance spawned from a cloud image.
    pub fn new() -> CloudInstance {
        CloudInstance {
            id: None,
            name: None,
            state: None,
            start_date: None,
            network_address: None,
            href: None,
            image: None,
            agent: None,
            error_message: None,
            error: None,
        }
    }
}

