/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CloudInstanceLocator : Represents a locator string for filtering CloudInstance entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloudInstanceLocator {
    /// Projects where the cloud profiles/images are accessible.
    #[serde(rename = "affectedProject", skip_serializing_if = "Option::is_none")]
    pub affected_project: Option<String>,
    /// Agent running on an instance.
    #[serde(rename = "agent", skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
    /// For paginated calls, how many entities to return per page.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Instance id as provided by list instances call.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Cloud image corresponding to an instance.
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    /// Instance network address.
    #[serde(rename = "networkAddress", skip_serializing_if = "Option::is_none")]
    pub network_address: Option<String>,
    /// Cloud profile of an instance.
    #[serde(rename = "profile", skip_serializing_if = "Option::is_none")]
    pub profile: Option<String>,
    /// Project defining the cloud profiles/images.
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(rename = "property", skip_serializing_if = "Option::is_none")]
    pub property: Option<String>,
    /// For paginated calls, from which entity to start rendering the page.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i64>,
}

impl CloudInstanceLocator {
    /// Represents a locator string for filtering CloudInstance entities.
    pub fn new() -> CloudInstanceLocator {
        CloudInstanceLocator {
            affected_project: None,
            agent: None,
            count: None,
            id: None,
            image: None,
            network_address: None,
            profile: None,
            project: None,
            property: None,
            start: None,
        }
    }
}

