/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Commiter : An author of a change committed to a VCS repository.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Commiter {
    /// The VCS username of a change author.
    #[serde(rename = "vcsUsername", skip_serializing_if = "Option::is_none")]
    pub vcs_username: Option<String>,
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Box<models::Users>>,
}

impl Commiter {
    /// An author of a change committed to a VCS repository.
    pub fn new() -> Commiter {
        Commiter {
            vcs_username: None,
            users: None,
        }
    }
}

