/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Compatibility : An entity that describes the compatibility relation between an agent and a build configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Compatibility {
    /// Returns *true* if the target agent is compatible with the given configuration (that is, can run its builds); otherwise, *false*.
    #[serde(rename = "compatible", skip_serializing_if = "Option::is_none")]
    pub compatible: Option<bool>,
    #[serde(rename = "agent", skip_serializing_if = "Option::is_none")]
    pub agent: Option<Box<models::Agent>>,
    #[serde(rename = "buildType", skip_serializing_if = "Option::is_none")]
    pub build_type: Option<Box<models::BuildType>>,
    #[serde(rename = "unmetRequirements", skip_serializing_if = "Option::is_none")]
    pub unmet_requirements: Option<Box<models::Requirements>>,
}

impl Compatibility {
    /// An entity that describes the compatibility relation between an agent and a build configuration.
    pub fn new() -> Compatibility {
        Compatibility {
            compatible: None,
            agent: None,
            build_type: None,
            unmet_requirements: None,
        }
    }
}

