/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Compatibilities : Represents a list of Compatibility entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Compatibilities {
    /// The current number of Compatibility objects in this list.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The list of Compatibility objects owned by this collection.
    #[serde(rename = "compatibility", skip_serializing_if = "Option::is_none")]
    pub compatibility: Option<Vec<models::Compatibility>>,
}

impl Compatibilities {
    /// Represents a list of Compatibility entities.
    pub fn new() -> Compatibilities {
        Compatibilities {
            count: None,
            compatibility: None,
        }
    }
}

