/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CompatibilityPolicy : Represents the policy that limit agents to building specific build configurations.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompatibilityPolicy {
    /// Returns whether the agent can run only builds of specific build configurations. Available values:  * *any* — agents with this policy can run builds of any build configurations. * *selected* — agents with this policy can only run builds of configurations stored in the `buildTypes` collection.
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<String>,
    #[serde(rename = "buildTypes", skip_serializing_if = "Option::is_none")]
    pub build_types: Option<Box<models::BuildTypes>>,
}

impl CompatibilityPolicy {
    /// Represents the policy that limit agents to building specific build configurations.
    pub fn new() -> CompatibilityPolicy {
        CompatibilityPolicy {
            policy: None,
            build_types: None,
        }
    }
}

