/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CompositeApprovals : Represents a list of CompositeApprovalRule entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompositeApprovals {
    /// The current number of CompositeApprovalRule objects in this collection.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The list of CompositeApprovalRule objects in this collection.
    #[serde(rename = "compositeApproval", skip_serializing_if = "Option::is_none")]
    pub composite_approval: Option<Vec<models::CompositeApprovalRule>>,
}

impl CompositeApprovals {
    /// Represents a list of CompositeApprovalRule entities.
    pub fn new() -> CompositeApprovals {
        CompositeApprovals {
            count: None,
            composite_approval: None,
        }
    }
}

