/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Cron : A cron expression that represents a custom schedule.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Cron {
    /// The minute of the scheduled time. Supports values in the 0 - 59 range.
    #[serde(rename = "minute", skip_serializing_if = "Option::is_none")]
    pub minute: Option<String>,
    /// The hour of the scheduled time. Supports Integer values in the 0 - 23 range and special.
    #[serde(rename = "hour", skip_serializing_if = "Option::is_none")]
    pub hour: Option<String>,
    /// The day of month when the scheduled event occurs. Supports Integer values in the 1 - 31 range and special characters.
    #[serde(rename = "day", skip_serializing_if = "Option::is_none")]
    pub day: Option<String>,
    /// The month when the scheduled event occurs. Supports Integer values in the 1-12 range, short month names (for example, **JAN**), and special characters.
    #[serde(rename = "month", skip_serializing_if = "Option::is_none")]
    pub month: Option<String>,
    /// The day of week when the scheduled event occurs. Supports Integer values in the 1-7 range, short month names (for example, **SAT**), and special characters.
    #[serde(rename = "dayWeek", skip_serializing_if = "Option::is_none")]
    pub day_week: Option<String>,
}

impl Cron {
    /// A cron expression that represents a custom schedule.
    pub fn new() -> Cron {
        Cron {
            minute: None,
            hour: None,
            day: None,
            month: None,
            day_week: None,
        }
    }
}

