/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Daily : The structure that represents a daily schedule.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Daily {
    /// The hour (in TeamCity server timezone) when the scheduled event should start.
    #[serde(rename = "hour", skip_serializing_if = "Option::is_none")]
    pub hour: Option<i32>,
    /// The minute (in TeamCity server timezone) when the scheduled event should start.
    #[serde(rename = "minute", skip_serializing_if = "Option::is_none")]
    pub minute: Option<i32>,
}

impl Daily {
    /// The structure that represents a daily schedule.
    pub fn new() -> Daily {
        Daily {
            hour: None,
            minute: None,
        }
    }
}

