/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeploymentInstances : Represents a paginated list of DeploymentInstance entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentInstances {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "nextHref", skip_serializing_if = "Option::is_none")]
    pub next_href: Option<String>,
    #[serde(rename = "prevHref", skip_serializing_if = "Option::is_none")]
    pub prev_href: Option<String>,
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "deploymentInstance", skip_serializing_if = "Option::is_none")]
    pub deployment_instance: Option<Vec<models::DeploymentInstance>>,
}

impl DeploymentInstances {
    /// Represents a paginated list of DeploymentInstance entities.
    pub fn new() -> DeploymentInstances {
        DeploymentInstances {
            count: None,
            next_href: None,
            prev_href: None,
            href: None,
            deployment_instance: None,
        }
    }
}

