/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeploymentInstance : Represents an instance that has been deployed to external system, along with deployment history.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentInstance {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "currentState", skip_serializing_if = "Option::is_none")]
    pub current_state: Option<CurrentState>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "deploymentStateEntries", skip_serializing_if = "Option::is_none")]
    pub deployment_state_entries: Option<Box<models::DeploymentStateEntries>>,
    #[serde(rename = "deploymentDashboard", skip_serializing_if = "Option::is_none")]
    pub deployment_dashboard: Option<Box<models::DeploymentDashboard>>,
}

impl DeploymentInstance {
    /// Represents an instance that has been deployed to external system, along with deployment history.
    pub fn new() -> DeploymentInstance {
        DeploymentInstance {
            id: None,
            current_state: None,
            attributes: None,
            deployment_state_entries: None,
            deployment_dashboard: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CurrentState {
    #[serde(rename = "IN_PROGRESS")]
    InProgress,
    #[serde(rename = "SUCCESSFUL")]
    Successful,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "CANCELLED")]
    Cancelled,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl Default for CurrentState {
    fn default() -> CurrentState {
        Self::InProgress
    }
}

