/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeploymentDashboard : Represents a deployment dashboard instance.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentDashboard {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "deploymentInstances", skip_serializing_if = "Option::is_none")]
    pub deployment_instances: Option<Box<models::DeploymentInstances>>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::Project>>,
}

impl DeploymentDashboard {
    /// Represents a deployment dashboard instance.
    pub fn new() -> DeploymentDashboard {
        DeploymentDashboard {
            id: None,
            name: None,
            deployment_instances: None,
            project: None,
        }
    }
}

