/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeploymentStateEntries : Represents a list of DeploymentStateEntry entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentStateEntries {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "historyFromPosted", skip_serializing_if = "Option::is_none")]
    pub history_from_posted: Option<Box<models::DeploymentHistory>>,
    #[serde(rename = "deploymentStateEntry", skip_serializing_if = "Option::is_none")]
    pub deployment_state_entry: Option<Vec<models::DeploymentStateEntry>>,
}

impl DeploymentStateEntries {
    /// Represents a list of DeploymentStateEntry entities.
    pub fn new() -> DeploymentStateEntries {
        DeploymentStateEntries {
            count: None,
            history_from_posted: None,
            deployment_state_entry: None,
        }
    }
}

