/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeploymentInstanceLocator : Represents a locator string for filtering DeploymentInstance entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentInstanceLocator {
    /// For paginated calls, how many entities to return per page.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Current state of deployment.
    #[serde(rename = "currentState", skip_serializing_if = "Option::is_none")]
    pub current_state: Option<CurrentState>,
    /// Deployment dashboard locator.
    #[serde(rename = "dashboard", skip_serializing_if = "Option::is_none")]
    pub dashboard: Option<String>,
    /// Dashboard id.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// For paginated calls, from which entity to start rendering the page.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i64>,
}

impl DeploymentInstanceLocator {
    /// Represents a locator string for filtering DeploymentInstance entities.
    pub fn new() -> DeploymentInstanceLocator {
        DeploymentInstanceLocator {
            count: None,
            current_state: None,
            dashboard: None,
            id: None,
            start: None,
        }
    }
}
/// Current state of deployment.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CurrentState {
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "successful")]
    Successful,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for CurrentState {
    fn default() -> CurrentState {
        Self::InProgress
    }
}

