/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentHistory {
    #[serde(rename = "currentState", skip_serializing_if = "Option::is_none")]
    pub current_state: Option<Box<models::DeploymentStateEntry>>,
    #[serde(rename = "states", skip_serializing_if = "Option::is_none")]
    pub states: Option<Vec<models::DeploymentStateEntry>>,
}

impl DeploymentHistory {
    pub fn new() -> DeploymentHistory {
        DeploymentHistory {
            current_state: None,
            states: None,
        }
    }
}

