/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DownloadedArtifacts : Stores information about all artifacts downloaded by this build.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownloadedArtifacts {
    /// The total number of artifacts downloaded by this build.
    #[serde(rename = "unfilteredCount", skip_serializing_if = "Option::is_none")]
    pub unfiltered_count: Option<i32>,
    /// Contains detailed information about downloaded files: the upstream build that provided artifacts, the number of artifacts delivered by this upstream build, and the individual file data.
    #[serde(rename = "downloadInfo", skip_serializing_if = "Option::is_none")]
    pub download_info: Option<Vec<models::DownloadInfo>>,
    /// The number of artifacts downloaded by this build, matching the number of DownloadInfo records. Can be lower than `unfilteredCount` if request locator filters out certain builds.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
}

impl DownloadedArtifacts {
    /// Stores information about all artifacts downloaded by this build.
    pub fn new() -> DownloadedArtifacts {
        DownloadedArtifacts {
            unfiltered_count: None,
            download_info: None,
            count: None,
        }
    }
}

