/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DownloadInfo : Stores information about all artifacts downloaded from one specific upstream build. Can be accessed via the `downloadInfo` field of the `DownloadedArtifacts` object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownloadInfo {
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<Box<models::Build>>,
    /// Stores individual records on each downloaded file.
    #[serde(rename = "artifactInfo", skip_serializing_if = "Option::is_none")]
    pub artifact_info: Option<Vec<models::ArtifactDownloadInfo>>,
    /// The number of files downloaded from the corresponding upstream build.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
}

impl DownloadInfo {
    /// Stores information about all artifacts downloaded from one specific upstream build. Can be accessed via the `downloadInfo` field of the `DownloadedArtifacts` object.
    pub fn new() -> DownloadInfo {
        DownloadInfo {
            build: None,
            artifact_info: None,
            count: None,
        }
    }
}

