/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EnabledResponsibilities : Represents a set of enabled responsibilities of a TeamCity node.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnabledResponsibilities {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "responsibility", skip_serializing_if = "Option::is_none")]
    pub responsibility: Option<Vec<models::Responsibility>>,
}

impl EnabledResponsibilities {
    /// Represents a set of enabled responsibilities of a TeamCity node.
    pub fn new() -> EnabledResponsibilities {
        EnabledResponsibilities {
            count: None,
            responsibility: None,
        }
    }
}

