/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Environment : Stores information about operating system installed on the agent machine.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Environment {
    /// The OS type.
    #[serde(rename = "osType", skip_serializing_if = "Option::is_none")]
    pub os_type: Option<String>,
    /// The full OS name
    #[serde(rename = "osName", skip_serializing_if = "Option::is_none")]
    pub os_name: Option<String>,
}

impl Environment {
    /// Stores information about operating system installed on the agent machine.
    pub fn new() -> Environment {
        Environment {
            os_type: None,
            os_name: None,
        }
    }
}

