/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// File : A file or a directory associated with, for instance, a published artifact.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct File {
    /// The public file name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The full name of a file, including all special characters omitted in the `name` property. Can be equal to `name`.
    #[serde(rename = "fullName", skip_serializing_if = "Option::is_none")]
    pub full_name: Option<String>,
    /// The file size in bytes.
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
    /// Returns the last time this file was edited.
    #[serde(rename = "modificationTime", skip_serializing_if = "Option::is_none")]
    pub modification_time: Option<String>,
    /// The link to file metadata object.
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<Box<models::File>>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<Box<models::Href>>,
    #[serde(rename = "children", skip_serializing_if = "Option::is_none")]
    pub children: Option<Box<models::Files>>,
}

impl File {
    /// A file or a directory associated with, for instance, a published artifact.
    pub fn new() -> File {
        File {
            name: None,
            full_name: None,
            size: None,
            modification_time: None,
            href: None,
            parent: None,
            content: None,
            children: None,
        }
    }
}

