/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileChanges : Represents a list of FileChange entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileChanges {
    /// The number of FileChange objects in this collection.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The list of FileChange objects owned by this collection.
    #[serde(rename = "file", skip_serializing_if = "Option::is_none")]
    pub file: Option<Vec<models::FileChange>>,
}

impl FileChanges {
    /// Represents a list of FileChange entities.
    pub fn new() -> FileChanges {
        FileChanges {
            count: None,
            file: None,
        }
    }
}

