/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Groups : Represents a list of Group entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Groups {
    /// The current number of Group objects in this collection.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The list of Group objects in this collection.
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<Vec<models::Group>>,
}

impl Groups {
    /// Represents a list of Group entities.
    pub fn new() -> Groups {
        Groups {
            count: None,
            group: None,
        }
    }
}

