/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HealthCategory : A health category that groups identical health items. Categories that group server-wide issues (`/app/rest/health?locator=global:true`) typically have one health item, whereas categories for project-specific issues can group multiple identical health items (one for each project where the issue manifests).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HealthCategory {
    /// The unique health category ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The public category name displayed in TeamCity UI as the category header.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The nullable health category description.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The link to TeamCity documentation or other resource that contains information on how to resolve a corresponding issue.
    #[serde(rename = "helpUrl", skip_serializing_if = "Option::is_none")]
    pub help_url: Option<String>,
}

impl HealthCategory {
    /// A health category that groups identical health items. Categories that group server-wide issues (`/app/rest/health?locator=global:true`) typically have one health item, whereas categories for project-specific issues can group multiple identical health items (one for each project where the issue manifests).
    pub fn new() -> HealthCategory {
        HealthCategory {
            id: None,
            name: None,
            description: None,
            help_url: None,
        }
    }
}

