/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Href : Represents a href link.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Href {
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
}

impl Href {
    /// Represents a href link.
    pub fn new() -> Href {
        Href {
            href: None,
        }
    }
}

