/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Link : Represents a list of URLs.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Link {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "relativeUrl", skip_serializing_if = "Option::is_none")]
    pub relative_url: Option<String>,
}

impl Link {
    /// Represents a list of URLs.
    pub fn new() -> Link {
        Link {
            r#type: None,
            url: None,
            relative_url: None,
        }
    }
}

