/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MatrixConfiguration : Stores unique matrix build settings. Matrix builds are virtual builds spawned by build configurations with the Matrix Build feature. This object is accessible via the `build.matrixConfiguration` field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatrixConfiguration {
    /// This is the internal property and is not intended to be used.
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<bool>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Box<models::MatrixBuildFeatureDescriptor>>,
    /// Returns *true* if the build feature is enabled; otherwise, *false*.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "dependencies", skip_serializing_if = "Option::is_none")]
    pub dependencies: Option<Box<models::MatrixDependencies>>,
}

impl MatrixConfiguration {
    /// Stores unique matrix build settings. Matrix builds are virtual builds spawned by build configurations with the Matrix Build feature. This object is accessible via the `build.matrixConfiguration` field.
    pub fn new() -> MatrixConfiguration {
        MatrixConfiguration {
            default: None,
            parameters: None,
            enabled: None,
            dependencies: None,
        }
    }
}

