/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MatrixDependency : Stores all combinations of Matrix Build parameter values and virtual builds that processed these combinations.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatrixDependency {
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<Box<models::Build>>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Box<models::Entries>>,
}

impl MatrixDependency {
    /// Stores all combinations of Matrix Build parameter values and virtual builds that processed these combinations.
    pub fn new() -> MatrixDependency {
        MatrixDependency {
            build: None,
            parameters: None,
        }
    }
}

