/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Type : Represents a build parameter type string.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Type {
    #[serde(rename = "rawValue", skip_serializing_if = "Option::is_none")]
    pub raw_value: Option<String>,
}

impl Type {
    /// Represents a build parameter type string.
    pub fn new() -> Type {
        Type {
            raw_value: None,
        }
    }
}

