/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MuteLocator : Represents a locator string for filtering Mute entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MuteLocator {
    /// Project affected by the mutes.
    #[serde(rename = "affectedProject", skip_serializing_if = "Option::is_none")]
    pub affected_project: Option<String>,
    /// Project with sub projects as well as parents.
    #[serde(rename = "affectedProjectAndParents", skip_serializing_if = "Option::is_none")]
    pub affected_project_and_parents: Option<String>,
    /// For paginated calls, how many entities to return per page.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Mute creation time, yyyyMMddTHHmmss+ZZZZ.
    #[serde(rename = "creationDate", skip_serializing_if = "Option::is_none")]
    pub creation_date: Option<String>,
    /// Internal mute id.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// Problem for which mute is assigned.
    #[serde(rename = "problem", skip_serializing_if = "Option::is_none")]
    pub problem: Option<String>,
    /// Project in which mute is assigned.
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    /// User who muted this test/problem.
    #[serde(rename = "reporter", skip_serializing_if = "Option::is_none")]
    pub reporter: Option<String>,
    /// Unmute condition.
    #[serde(rename = "resolution", skip_serializing_if = "Option::is_none")]
    pub resolution: Option<Resolution>,
    /// For paginated calls, from which entity to start rendering the page.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i64>,
    /// test for which mute is assigned
    #[serde(rename = "test", skip_serializing_if = "Option::is_none")]
    pub test: Option<String>,
    /// What is muted.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    /// Automatic unmute time, yyyyMMddTHHmmss+ZZZZ.
    #[serde(rename = "unmuteDate", skip_serializing_if = "Option::is_none")]
    pub unmute_date: Option<String>,
}

impl MuteLocator {
    /// Represents a locator string for filtering Mute entities.
    pub fn new() -> MuteLocator {
        MuteLocator {
            affected_project: None,
            affected_project_and_parents: None,
            count: None,
            creation_date: None,
            id: None,
            problem: None,
            project: None,
            reporter: None,
            resolution: None,
            start: None,
            test: None,
            r#type: None,
            unmute_date: None,
        }
    }
}
/// Unmute condition.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Resolution {
    #[serde(rename = "manually")]
    Manually,
    #[serde(rename = "whenfixed")]
    Whenfixed,
    #[serde(rename = "attime")]
    Attime,
}

impl Default for Resolution {
    fn default() -> Resolution {
        Self::Manually
    }
}
/// What is muted.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "test")]
    Test,
    #[serde(rename = "problem")]
    Problem,
}

impl Default for Type {
    fn default() -> Type {
        Self::Test
    }
}

