/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Mutes : Represents a paginated list of Mute entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mutes {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "nextHref", skip_serializing_if = "Option::is_none")]
    pub next_href: Option<String>,
    #[serde(rename = "prevHref", skip_serializing_if = "Option::is_none")]
    pub prev_href: Option<String>,
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "mute", skip_serializing_if = "Option::is_none")]
    pub mute: Option<Vec<models::Mute>>,
}

impl Mutes {
    /// Represents a paginated list of Mute entities.
    pub fn new() -> Mutes {
        Mutes {
            count: None,
            next_href: None,
            prev_href: None,
            href: None,
            mute: None,
        }
    }
}

