/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Mute : Represents a muted test.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mute {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "assignment", skip_serializing_if = "Option::is_none")]
    pub assignment: Option<Box<models::Comment>>,
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<Box<models::ProblemScope>>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<Box<models::ProblemTarget>>,
    #[serde(rename = "resolution", skip_serializing_if = "Option::is_none")]
    pub resolution: Option<Box<models::Resolution>>,
}

impl Mute {
    /// Represents a muted test.
    pub fn new() -> Mute {
        Mute {
            id: None,
            href: None,
            assignment: None,
            scope: None,
            target: None,
            resolution: None,
        }
    }
}

