/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ParsedTestName : Represents test metadata (package, method, class, and so on).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParsedTestName {
    #[serde(rename = "testPackage", skip_serializing_if = "Option::is_none")]
    pub test_package: Option<String>,
    #[serde(rename = "testSuite", skip_serializing_if = "Option::is_none")]
    pub test_suite: Option<String>,
    #[serde(rename = "testClass", skip_serializing_if = "Option::is_none")]
    pub test_class: Option<String>,
    #[serde(rename = "testShortName", skip_serializing_if = "Option::is_none")]
    pub test_short_name: Option<String>,
    #[serde(rename = "testNameWithoutPrefix", skip_serializing_if = "Option::is_none")]
    pub test_name_without_prefix: Option<String>,
    #[serde(rename = "testMethodName", skip_serializing_if = "Option::is_none")]
    pub test_method_name: Option<String>,
    #[serde(rename = "testNameWithParameters", skip_serializing_if = "Option::is_none")]
    pub test_name_with_parameters: Option<String>,
}

impl ParsedTestName {
    /// Represents test metadata (package, method, class, and so on).
    pub fn new() -> ParsedTestName {
        ParsedTestName {
            test_package: None,
            test_suite: None,
            test_class: None,
            test_short_name: None,
            test_name_without_prefix: None,
            test_method_name: None,
            test_name_with_parameters: None,
        }
    }
}

