/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PermissionAssignment : The object that defines a project scope for a permission. Objects of this class should not be created manually; TeamCity returns one when you retrieve a list of user permissions via the `/app/rest/users/{userLocator}/permissions` endpoint.`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PermissionAssignment {
    /// Returns **false** if the permission was granted to a user for a specific project only. Returns **true** for global permissions (for example, the `change_own_profile` permission) and project-specific permissions that were assigned globally (for example, the `view_file_content` permission included in a role that was [granted to a group](https://www.jetbrains.com/help/teamcity/rest/groupapi.html#addRoleToGroup) with `'scope': 'g'` in the request body).
    #[serde(rename = "isGlobalScope", skip_serializing_if = "Option::is_none")]
    pub is_global_scope: Option<bool>,
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<Box<models::Permission>>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::Project>>,
}

impl PermissionAssignment {
    /// The object that defines a project scope for a permission. Objects of this class should not be created manually; TeamCity returns one when you retrieve a list of user permissions via the `/app/rest/users/{userLocator}/permissions` endpoint.`
    pub fn new() -> PermissionAssignment {
        PermissionAssignment {
            is_global_scope: None,
            permission: None,
            project: None,
        }
    }
}

