/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PermissionAssignments : Represents a list of PermissionAssignment entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PermissionAssignments {
    /// The current number of PermissionAssignment objects in this collection.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The list of PermissionAssignment objects in this collection.
    #[serde(rename = "permissionAssignment", skip_serializing_if = "Option::is_none")]
    pub permission_assignment: Option<Vec<models::PermissionAssignment>>,
}

impl PermissionAssignments {
    /// Represents a list of PermissionAssignment entities.
    pub fn new() -> PermissionAssignments {
        PermissionAssignments {
            count: None,
            permission_assignment: None,
        }
    }
}

