/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PermissionRestriction : When [issuing access tokens](https://www.jetbrains.com/help/teamcity/configuring-your-user-profile.html#Managing+Access+Tokens), users can grant them the same permissions they have or restrict them to specific actions within selected projects. **PermissionRestriction** objects define these project-level permissions for tokens with reduced access (compared to the issuing user).   To issue a personal token with limited access via REST API, send a `POST` request to the [/app/rest/users/{userLocator}/tokens](https://www.jetbrains.com/help/teamcity/rest/userapi.html#addUserToken) endpoint and specify the PermissionRestrictions collection in the request body.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PermissionRestriction {
    /// Returns **false** if the permission was granted to an access token for a specific project only. Returns **true** for global permissions (for example, the `change_own_profile` permission) and project-specific permissions that were assigned globally (for example, the `authorize_agent` permission is granted on the Root project level).
    #[serde(rename = "isGlobalScope", skip_serializing_if = "Option::is_none")]
    pub is_global_scope: Option<bool>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::Project>>,
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<Box<models::Permission>>,
}

impl PermissionRestriction {
    /// When [issuing access tokens](https://www.jetbrains.com/help/teamcity/configuring-your-user-profile.html#Managing+Access+Tokens), users can grant them the same permissions they have or restrict them to specific actions within selected projects. **PermissionRestriction** objects define these project-level permissions for tokens with reduced access (compared to the issuing user).   To issue a personal token with limited access via REST API, send a `POST` request to the [/app/rest/users/{userLocator}/tokens](https://www.jetbrains.com/help/teamcity/rest/userapi.html#addUserToken) endpoint and specify the PermissionRestrictions collection in the request body.
    pub fn new() -> PermissionRestriction {
        PermissionRestriction {
            is_global_scope: None,
            project: None,
            permission: None,
        }
    }
}

