/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Permission : A permission that defines a specific action (or set of actions) a TeamCity user can perform. The non-editable list of user permissions is available via the `/app/rest/users/{userLocator}/permissions` endpoint. Permissions are granted to roles, which can then be attached to user groups or individual users.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Permission {
    /// The unique permission ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The read-only description of this permission
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Returns **true** if the permission can be assigned only globally (for example, the `view_audit_log` permission); **false** if it can be limited to a specific TeamCity project (`cancel_build` or `view_project`).   This property is a characteristic of a permission itself and does not reflect how this permission is used in a specific role for a specific user. Users can be granted a non-global permission (either directly or by joining a user group) both for individual projects and globally (for all projects on a server). For example, when [assigning a role to an individual user](https://www.jetbrains.com/help/teamcity/rest/userapi.html#addRoleToUser), a request body can set the `scope` parameter to either `g` (global) or `p:{Project_ID}`. The actual permission scope for a specific user is stored in the [PermissionAssignment.isGlobalScope](https://www.jetbrains.com/help/teamcity/rest/permissionassignment.html) property.
    #[serde(rename = "global", skip_serializing_if = "Option::is_none")]
    pub global: Option<bool>,
}

impl Permission {
    /// A permission that defines a specific action (or set of actions) a TeamCity user can perform. The non-editable list of user permissions is available via the `/app/rest/users/{userLocator}/permissions` endpoint. Permissions are granted to roles, which can then be attached to user groups or individual users.
    pub fn new() -> Permission {
        Permission {
            id: None,
            name: None,
            global: None,
        }
    }
}

