/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProblemLocator : Represents a locator string for filtering Problem entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProblemLocator {
    /// Project (direct or indirect parent) locator.
    #[serde(rename = "affectedProject", skip_serializing_if = "Option::is_none")]
    pub affected_project: Option<String>,
    /// Build locator.
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<String>,
    /// For paginated calls, how many entities to return per page.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// Is currently failing.
    #[serde(rename = "currentlyFailing", skip_serializing_if = "Option::is_none")]
    pub currently_failing: Option<bool>,
    /// Is currently investigated.
    #[serde(rename = "currentlyInvestigated", skip_serializing_if = "Option::is_none")]
    pub currently_investigated: Option<bool>,
    /// Is currently muted.
    #[serde(rename = "currentlyMuted", skip_serializing_if = "Option::is_none")]
    pub currently_muted: Option<bool>,
    /// Entity ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<String>,
    /// Supply multiple locators and return a union of the results.
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<String>,
    /// Limit processing to the latest `<lookupLimit>` entities.
    #[serde(rename = "lookupLimit", skip_serializing_if = "Option::is_none")]
    pub lookup_limit: Option<i32>,
    /// For paginated calls, from which entity to start rendering the page.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i32>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl ProblemLocator {
    /// Represents a locator string for filtering Problem entities.
    pub fn new() -> ProblemLocator {
        ProblemLocator {
            affected_project: None,
            build: None,
            count: None,
            currently_failing: None,
            currently_investigated: None,
            currently_muted: None,
            id: None,
            identity: None,
            item: None,
            lookup_limit: None,
            start: None,
            r#type: None,
        }
    }
}

