/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProblemScope : The investigation scope that allows you to identify whether the problem scope is limited to the specific configurations or an entire project.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProblemScope {
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::Project>>,
    #[serde(rename = "buildTypes", skip_serializing_if = "Option::is_none")]
    pub build_types: Option<Box<models::BuildTypes>>,
    #[serde(rename = "buildType", skip_serializing_if = "Option::is_none")]
    pub build_type: Option<Box<models::BuildType>>,
}

impl ProblemScope {
    /// The investigation scope that allows you to identify whether the problem scope is limited to the specific configurations or an entire project.
    pub fn new() -> ProblemScope {
        ProblemScope {
            project: None,
            build_types: None,
            build_type: None,
        }
    }
}

