/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProgressInfo : An object that stores the latest information about a currently running build. Returns an empty object for finished and queued builds.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProgressInfo {
    /// The current completion rate (in percents).
    #[serde(rename = "percentageComplete", skip_serializing_if = "Option::is_none")]
    pub percentage_complete: Option<i32>,
    /// Time (in seconds) passed since the build actually started. Does not include time spent in queue.
    #[serde(rename = "elapsedSeconds", skip_serializing_if = "Option::is_none")]
    pub elapsed_seconds: Option<i64>,
    /// The currently estimated build duration (in seconds). The sum of `elapsedSeconds`, `leftSeconds`, and post-build activity duration.
    #[serde(rename = "estimatedTotalSeconds", skip_serializing_if = "Option::is_none")]
    pub estimated_total_seconds: Option<i64>,
    /// The estimated remaining build time (in seconds)
    #[serde(rename = "leftSeconds", skip_serializing_if = "Option::is_none")]
    pub left_seconds: Option<i64>,
    /// The description of the currently performed build stage. Combines the build status with the latest build log message.
    #[serde(rename = "currentStageText", skip_serializing_if = "Option::is_none")]
    pub current_stage_text: Option<String>,
    /// Returns *true* for [history builds](https://www.jetbrains.com/help/teamcity/history-build.html). Builds are labeled as outdated (history) if there are finished non-personal builds that processed newer (or same) changes as in this build.
    #[serde(rename = "outdated", skip_serializing_if = "Option::is_none")]
    pub outdated: Option<bool>,
    /// Returns *true* if the server suspects this build is hanging. Builds are considered hung when their run duration exceeds the estimates and the build sends no new messages for some time.
    #[serde(rename = "probablyHanging", skip_serializing_if = "Option::is_none")]
    pub probably_hanging: Option<bool>,
    /// The timestamp of the latest build log message.
    #[serde(rename = "lastActivityTime", skip_serializing_if = "Option::is_none")]
    pub last_activity_time: Option<String>,
    #[serde(rename = "outdatedReasonBuild", skip_serializing_if = "Option::is_none")]
    pub outdated_reason_build: Option<Box<models::Build>>,
}

impl ProgressInfo {
    /// An object that stores the latest information about a currently running build. Returns an empty object for finished and queued builds.
    pub fn new() -> ProgressInfo {
        ProgressInfo {
            percentage_complete: None,
            elapsed_seconds: None,
            estimated_total_seconds: None,
            left_seconds: None,
            current_stage_text: None,
            outdated: None,
            probably_hanging: None,
            last_activity_time: None,
            outdated_reason_build: None,
        }
    }
}

