/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectLocator : Represents a locator string for filtering Project entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectLocator {
    /// Project (direct or indirect parent) locator.
    #[serde(rename = "affectedProject", skip_serializing_if = "Option::is_none")]
    pub affected_project: Option<String>,
    /// Is archived.
    #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
    pub archived: Option<bool>,
    /// Build locator.
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<String>,
    /// Build type locator.
    #[serde(rename = "buildType", skip_serializing_if = "Option::is_none")]
    pub build_type: Option<String>,
    /// For paginated calls, how many entities to return per page.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// Default template locator.
    #[serde(rename = "defaultTemplate", skip_serializing_if = "Option::is_none")]
    pub default_template: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<String>,
    /// Supply multiple locators and return a union of the results.
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Associated agent pool locator.
    #[serde(rename = "pool", skip_serializing_if = "Option::is_none")]
    pub pool: Option<String>,
    /// Project (direct parent) locator.
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    /// Project feature locator.
    #[serde(rename = "projectFeature", skip_serializing_if = "Option::is_none")]
    pub project_feature: Option<String>,
    /// For paginated calls, from which entity to start rendering the page.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i32>,
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    /// VCS root locator.
    #[serde(rename = "vcsRoot", skip_serializing_if = "Option::is_none")]
    pub vcs_root: Option<String>,
    /// Is virtual (default=false).
    #[serde(rename = "virtual", skip_serializing_if = "Option::is_none")]
    pub r#virtual: Option<bool>,
}

impl ProjectLocator {
    /// Represents a locator string for filtering Project entities.
    pub fn new() -> ProjectLocator {
        ProjectLocator {
            affected_project: None,
            archived: None,
            build: None,
            build_type: None,
            count: None,
            default_template: None,
            id: None,
            internal_id: None,
            item: None,
            name: None,
            pool: None,
            project: None,
            project_feature: None,
            start: None,
            uuid: None,
            vcs_root: None,
            r#virtual: None,
        }
    }
}

