/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Properties : Represents a list of Property entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Properties {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "property", skip_serializing_if = "Option::is_none")]
    pub property: Option<Vec<models::Property>>,
}

impl Properties {
    /// Represents a list of Property entities.
    pub fn new() -> Properties {
        Properties {
            count: None,
            href: None,
            property: None,
        }
    }
}

