/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RelatedEntities : Represents a list of RelatedEntity entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RelatedEntities {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "entity", skip_serializing_if = "Option::is_none")]
    pub entity: Option<Vec<models::RelatedEntity>>,
}

impl RelatedEntities {
    /// Represents a list of RelatedEntity entities.
    pub fn new() -> RelatedEntities {
        RelatedEntities {
            count: None,
            entity: None,
        }
    }
}

