/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RelatedEntity : Represents a related entity.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RelatedEntity {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "unknown", skip_serializing_if = "Option::is_none")]
    pub unknown: Option<bool>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<String>,
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<Box<models::Build>>,
    #[serde(rename = "buildType", skip_serializing_if = "Option::is_none")]
    pub build_type: Option<Box<models::BuildType>>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::Project>>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::User>>,
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<Box<models::Group>>,
    #[serde(rename = "test", skip_serializing_if = "Option::is_none")]
    pub test: Option<Box<models::Test>>,
    #[serde(rename = "problem", skip_serializing_if = "Option::is_none")]
    pub problem: Option<Box<models::Problem>>,
    #[serde(rename = "agent", skip_serializing_if = "Option::is_none")]
    pub agent: Option<Box<models::Agent>>,
    #[serde(rename = "vcsRoot", skip_serializing_if = "Option::is_none")]
    pub vcs_root: Option<Box<models::VcsRoot>>,
    #[serde(rename = "change", skip_serializing_if = "Option::is_none")]
    pub change: Option<Box<models::Change>>,
    #[serde(rename = "agentPool", skip_serializing_if = "Option::is_none")]
    pub agent_pool: Option<Box<models::AgentPool>>,
}

impl RelatedEntity {
    /// Represents a related entity.
    pub fn new() -> RelatedEntity {
        RelatedEntity {
            r#type: None,
            unknown: None,
            internal_id: None,
            text: None,
            build: None,
            build_type: None,
            project: None,
            user: None,
            group: None,
            test: None,
            problem: None,
            agent: None,
            vcs_root: None,
            change: None,
            agent_pool: None,
        }
    }
}

