/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RepositoryState : Represents the list of the repository Branch entities with their recent revisions.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryState {
    /// Specifies when this RepositoryState object was created.
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    /// The length of the `branches` collection.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The list of repository branches.
    #[serde(rename = "branch", skip_serializing_if = "Option::is_none")]
    pub branch: Option<Vec<models::BranchVersion>>,
}

impl RepositoryState {
    /// Represents the list of the repository Branch entities with their recent revisions.
    pub fn new() -> RepositoryState {
        RepositoryState {
            timestamp: None,
            count: None,
            branch: None,
        }
    }
}

