/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Requirements : The list of unmet requirements that prevents an agent to run the target build. Most commongly used in [`Compatibility`](https://www.jetbrains.com/help/teamcity/rest/compatibility.html) objects.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Requirements {
    /// The summary of all unment requirements that make the target agent incompatible with the given configuration.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl Requirements {
    /// The list of unmet requirements that prevents an agent to run the target build. Most commongly used in [`Compatibility`](https://www.jetbrains.com/help/teamcity/rest/compatibility.html) objects.
    pub fn new() -> Requirements {
        Requirements {
            description: None,
        }
    }
}

