/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Resolution : Represents an investigation resolution timestamp and details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Resolution {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
}

impl Resolution {
    /// Represents an investigation resolution timestamp and details.
    pub fn new() -> Resolution {
        Resolution {
            r#type: None,
            time: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "manually")]
    Manually,
    #[serde(rename = "whenFixed")]
    WhenFixed,
    #[serde(rename = "atTime")]
    AtTime,
}

impl Default for Type {
    fn default() -> Type {
        Self::Manually
    }
}

