/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Responsibility : Represents a single responsibility of a TeamCity node.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Responsibility {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl Responsibility {
    /// Represents a single responsibility of a TeamCity node.
    pub fn new() -> Responsibility {
        Responsibility {
            name: None,
            description: None,
        }
    }
}

