/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Revisions : Represents a list of Revision entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Revisions {
    /// The number of Revision objects in this collection.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The list of Revision objects owned by this collection.
    #[serde(rename = "revision", skip_serializing_if = "Option::is_none")]
    pub revision: Option<Vec<models::Revision>>,
    /// **true** if the build should fail when child Revision objects are missing valid `version` values; **false** if in this case a build should process latest changes.
    #[serde(rename = "failOnMissingRevisions", skip_serializing_if = "Option::is_none")]
    pub fail_on_missing_revisions: Option<bool>,
}

impl Revisions {
    /// Represents a list of Revision entities.
    pub fn new() -> Revisions {
        Revisions {
            count: None,
            revision: None,
            fail_on_missing_revisions: None,
        }
    }
}

