/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RoleAssignments : The collection of RoleAssignment objects.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleAssignments {
    /// The list of RoleAssigment objects in this collection.
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<Vec<models::RoleAssignment>>,
}

impl RoleAssignments {
    /// The collection of RoleAssignment objects.
    pub fn new() -> RoleAssignments {
        RoleAssignments {
            role: None,
        }
    }
}

