/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SnapshotDependencies : Represents a list of SnapshotDependency entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SnapshotDependencies {
    /// The number of `snapshot-dependency` objects in this collection.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The list of `snapshot-dependency` objects owned by this collection.
    #[serde(rename = "snapshot-dependency", skip_serializing_if = "Option::is_none")]
    pub snapshot_dependency: Option<Vec<models::SnapshotDependency>>,
}

impl SnapshotDependencies {
    /// Represents a list of SnapshotDependency entities.
    pub fn new() -> SnapshotDependencies {
        SnapshotDependencies {
            count: None,
            snapshot_dependency: None,
        }
    }
}

