/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SnapshotDependency : A snapshot dependency that specifies the relation between the current (dependent) downstream configuration of a build chain, and an upstream configuration on which the current configuration depends.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SnapshotDependency {
    /// The internal read-only ID of the object. This property is inherited from the base PropEntity class.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The public object name. Some objects, like build steps, support public names, while others, like build triggers, do not. This property is inherited from the base PropEntity class.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The object type. This property is inherited from the base PropEntity class.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Returns **rue** if the object is disabled and inactive; otherwise, **false**. This property is inherited from the base PropEntity class.
    #[serde(rename = "disabled", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
    /// Returns **rue** if the object is inherited from another object; otherwise, **false**. This property is inherited from the base PropEntity class.
    #[serde(rename = "inherited", skip_serializing_if = "Option::is_none")]
    pub inherited: Option<bool>,
    /// Returns the shortened (without the server URL) link to the current object. This property is inherited from the base PropEntity class.
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<models::Properties>>,
    #[serde(rename = "source-buildType", skip_serializing_if = "Option::is_none")]
    pub source_build_type: Option<Box<models::BuildType>>,
}

impl SnapshotDependency {
    /// A snapshot dependency that specifies the relation between the current (dependent) downstream configuration of a build chain, and an upstream configuration on which the current configuration depends.
    pub fn new() -> SnapshotDependency {
        SnapshotDependency {
            id: None,
            name: None,
            r#type: None,
            disabled: None,
            inherited: None,
            href: None,
            properties: None,
            source_build_type: None,
        }
    }
}

