/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SnapshotDependencyLink : The link to the upstream build of a chain that processed this change. If a downstream build of a chain includes a change that was already processed by an upstream build, this change's type equals `SNAPSHOT_DEPENDENCY_VCS_CHANGE` and its `snapshotDependencyLink` property stores data about this upstream build.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SnapshotDependencyLink {
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<Box<models::Build>>,
    #[serde(rename = "buildType", skip_serializing_if = "Option::is_none")]
    pub build_type: Option<Box<models::BuildType>>,
    /// The branch of build configuration that was targeted by an upstream build.
    #[serde(rename = "buildTypeBranch", skip_serializing_if = "Option::is_none")]
    pub build_type_branch: Option<String>,
}

impl SnapshotDependencyLink {
    /// The link to the upstream build of a chain that processed this change. If a downstream build of a chain includes a change that was already processed by an upstream build, this change's type equals `SNAPSHOT_DEPENDENCY_VCS_CHANGE` and its `snapshotDependencyLink` property stores data about this upstream build.
    pub fn new() -> SnapshotDependencyLink {
        SnapshotDependencyLink {
            build: None,
            build_type: None,
            build_type_branch: None,
        }
    }
}

