/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StateField : Represents a project state field (as of now, limited to the read-only state of project).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StateField {
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<bool>,
    #[serde(rename = "inherited", skip_serializing_if = "Option::is_none")]
    pub inherited: Option<bool>,
}

impl StateField {
    /// Represents a project state field (as of now, limited to the read-only state of project).
    pub fn new() -> StateField {
        StateField {
            value: None,
            inherited: None,
        }
    }
}

