/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Steps : Represents a list of Step entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Steps {
    /// The number of build steps in this collection.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// Build steps owned by this collection.
    #[serde(rename = "step", skip_serializing_if = "Option::is_none")]
    pub step: Option<Vec<models::Step>>,
}

impl Steps {
    /// Represents a list of Step entities.
    pub fn new() -> Steps {
        Steps {
            count: None,
            step: None,
        }
    }
}

