/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TagLocator : Represents a locator string for filtering Tag entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagLocator {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    #[serde(rename = "private", skip_serializing_if = "Option::is_none")]
    pub private: Option<String>,
}

impl TagLocator {
    /// Represents a locator string for filtering Tag entities.
    pub fn new() -> TagLocator {
        TagLocator {
            name: None,
            owner: None,
            private: None,
        }
    }
}

