/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Tags : Represents a list of Tag entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tags {
    /// The current number of Tag objects in this list.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The list of tags owned by this collection that satisfy the given locator.
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<Vec<models::Tag>>,
}

impl Tags {
    /// Represents a list of Tag entities.
    pub fn new() -> Tags {
        Tags {
            count: None,
            tag: None,
        }
    }
}

