/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TeamCityNodeLocator : Represents a locator string for filtering Node entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamCityNodeLocator {
    /// Supply multiple locators and return a union of the results.
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<String>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
}

impl TeamCityNodeLocator {
    /// Represents a locator string for filtering Node entities.
    pub fn new() -> TeamCityNodeLocator {
        TeamCityNodeLocator {
            item: None,
            role: None,
            state: None,
        }
    }
}

