/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TestOccurrenceLocator : Represents a locator string for filtering TestOccurrence entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TestOccurrenceLocator {
    /// Project (direct or indirect parent) locator.
    #[serde(rename = "affectedProject", skip_serializing_if = "Option::is_none")]
    pub affected_project: Option<String>,
    #[serde(rename = "branch", skip_serializing_if = "Option::is_none")]
    pub branch: Option<String>,
    /// Build locator.
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<String>,
    /// Build type locator.
    #[serde(rename = "buildType", skip_serializing_if = "Option::is_none")]
    pub build_type: Option<String>,
    /// For paginated calls, how many entities to return per page.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// Is currently failing.
    #[serde(rename = "currentlyFailing", skip_serializing_if = "Option::is_none")]
    pub currently_failing: Option<bool>,
    /// Is currently investigated.
    #[serde(rename = "currentlyInvestigated", skip_serializing_if = "Option::is_none")]
    pub currently_investigated: Option<bool>,
    #[serde(rename = "currentlyMuted", skip_serializing_if = "Option::is_none")]
    pub currently_muted: Option<String>,
    /// Entity ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Is ignored.
    #[serde(rename = "ignored", skip_serializing_if = "Option::is_none")]
    pub ignored: Option<bool>,
    #[serde(rename = "includePersonal", skip_serializing_if = "Option::is_none")]
    pub include_personal: Option<bool>,
    /// Supply multiple locators and return a union of the results.
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<String>,
    /// Limit processing to the latest `<lookupLimit>` entities.
    #[serde(rename = "lookupLimit", skip_serializing_if = "Option::is_none")]
    pub lookup_limit: Option<i32>,
    /// Is muted.
    #[serde(rename = "muted", skip_serializing_if = "Option::is_none")]
    pub muted: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "newFailure", skip_serializing_if = "Option::is_none")]
    pub new_failure: Option<String>,
    /// For paginated calls, from which entity to start rendering the page.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i32>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Test locator.
    #[serde(rename = "test", skip_serializing_if = "Option::is_none")]
    pub test: Option<String>,
}

impl TestOccurrenceLocator {
    /// Represents a locator string for filtering TestOccurrence entities.
    pub fn new() -> TestOccurrenceLocator {
        TestOccurrenceLocator {
            affected_project: None,
            branch: None,
            build: None,
            build_type: None,
            count: None,
            currently_failing: None,
            currently_investigated: None,
            currently_muted: None,
            id: None,
            ignored: None,
            include_personal: None,
            item: None,
            lookup_limit: None,
            muted: None,
            name: None,
            new_failure: None,
            start: None,
            status: None,
            test: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "normal")]
    Normal,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "failure")]
    Failure,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "success")]
    Success,
}

impl Default for Status {
    fn default() -> Status {
        Self::Unknown
    }
}

