/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Tests : Represents a paginated list of Test entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tests {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "myTestCounters", skip_serializing_if = "Option::is_none")]
    pub my_test_counters: Option<Box<models::TestCounters>>,
    #[serde(rename = "nextHref", skip_serializing_if = "Option::is_none")]
    pub next_href: Option<String>,
    #[serde(rename = "prevHref", skip_serializing_if = "Option::is_none")]
    pub prev_href: Option<String>,
    #[serde(rename = "test", skip_serializing_if = "Option::is_none")]
    pub test: Option<Vec<models::Test>>,
}

impl Tests {
    /// Represents a paginated list of Test entities.
    pub fn new() -> Tests {
        Tests {
            count: None,
            my_test_counters: None,
            next_href: None,
            prev_href: None,
            test: None,
        }
    }
}

