/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Triggers : Represents a list of Trigger entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Triggers {
    /// The number of triggers in this collection.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The list of triggers owned by this collection.
    #[serde(rename = "trigger", skip_serializing_if = "Option::is_none")]
    pub trigger: Option<Vec<models::Trigger>>,
}

impl Triggers {
    /// Represents a list of Trigger entities.
    pub fn new() -> Triggers {
        Triggers {
            count: None,
            trigger: None,
        }
    }
}

