/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TriggeredBy : Identifies the authority that triggered this build.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TriggeredBy {
    /// Returns the following values depending on the authority that triggered this build:   * *user* if the build was triggered manually in TeamCity UI or via REST API. * *snapshotDependency* if the build is a part of a build chain and was requested by a downstream build configuration. * *vcs* if the build was initiated by the VCS Trigger that found new commits in the remote repository. * *schedule* if the build was initiated by the Schedule Trigger. * *finishBuild* if the build was initiated by the Finish Build Trigger. * *retry* if the build was initiated by the Retry Trigger that re-starts failed builds.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Optional details regarding the triggering event.
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    /// The timestamp of the build triggering.
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// The summary displayed next to the 'Triggered' line in TeamCity UI. Enumerates authorities that caused this build to run and displays the build's parent configuration name and number.
    #[serde(rename = "displayText", skip_serializing_if = "Option::is_none")]
    pub display_text: Option<String>,
    /// The string representation of the `properties` array.
    #[serde(rename = "rawValue", skip_serializing_if = "Option::is_none")]
    pub raw_value: Option<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::User>>,
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<Box<models::Build>>,
    #[serde(rename = "buildType", skip_serializing_if = "Option::is_none")]
    pub build_type: Option<Box<models::BuildType>>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<models::Properties>>,
}

impl TriggeredBy {
    /// Identifies the authority that triggered this build.
    pub fn new() -> TriggeredBy {
        TriggeredBy {
            r#type: None,
            details: None,
            date: None,
            display_text: None,
            raw_value: None,
            user: None,
            build: None,
            build_type: None,
            properties: None,
        }
    }
}

