/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserAvatars : A collection of links to the current user profile picture rescaled to different sizes.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAvatars {
    /// The relative (without the TeamCity server URL) link to the user profile picture rescaled to 20x20 pixels.
    #[serde(rename = "urlToSize20", skip_serializing_if = "Option::is_none")]
    pub url_to_size20: Option<String>,
    /// The relative (without the TeamCity server URL) link to the user profile picture rescaled to 28x28 pixels.
    #[serde(rename = "urlToSize28", skip_serializing_if = "Option::is_none")]
    pub url_to_size28: Option<String>,
    /// The relative (without the TeamCity server URL) link to the user profile picture rescaled to 32x32 pixels.
    #[serde(rename = "urlToSize32", skip_serializing_if = "Option::is_none")]
    pub url_to_size32: Option<String>,
    /// The relative (without the TeamCity server URL) link to the user profile picture rescaled to 40x40 pixels.
    #[serde(rename = "urlToSize40", skip_serializing_if = "Option::is_none")]
    pub url_to_size40: Option<String>,
    /// The relative (without the TeamCity server URL) link to the user profile picture rescaled to 56x56 pixels.
    #[serde(rename = "urlToSize56", skip_serializing_if = "Option::is_none")]
    pub url_to_size56: Option<String>,
    /// The relative (without the TeamCity server URL) link to the user profile picture rescaled to 64x64 pixels.
    #[serde(rename = "urlToSize64", skip_serializing_if = "Option::is_none")]
    pub url_to_size64: Option<String>,
    /// The relative (without the TeamCity server URL) link to the user profile picture rescaled to 80x80 pixels.
    #[serde(rename = "urlToSize80", skip_serializing_if = "Option::is_none")]
    pub url_to_size80: Option<String>,
}

impl UserAvatars {
    /// A collection of links to the current user profile picture rescaled to different sizes.
    pub fn new() -> UserAvatars {
        UserAvatars {
            url_to_size20: None,
            url_to_size28: None,
            url_to_size32: None,
            url_to_size40: None,
            url_to_size56: None,
            url_to_size64: None,
            url_to_size80: None,
        }
    }
}

