/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserApprovalRule : An individual user approval rule and its current status for the given build.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserApprovalRule {
    /// Returns *true* if this user already approved the build; otherwise, *false*
    #[serde(rename = "approved", skip_serializing_if = "Option::is_none")]
    pub approved: Option<bool>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::User>>,
}

impl UserApprovalRule {
    /// An individual user approval rule and its current status for the given build.
    pub fn new() -> UserApprovalRule {
        UserApprovalRule {
            approved: None,
            user: None,
        }
    }
}

