/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Users : Represents a list of User entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Users {
    /// The current number of User objects in this collection.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The list of User objects in this collection.
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Vec<models::User>>,
}

impl Users {
    /// Represents a list of User entities.
    pub fn new() -> Users {
        Users {
            count: None,
            user: None,
        }
    }
}

