/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// User : A TeamCity user account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    /// The mandatory username.
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// The public user name, or **null** if not specified.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The unique user account ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// The date and time when this user last logged in TeamCity.
    #[serde(rename = "lastLogin", skip_serializing_if = "Option::is_none")]
    pub last_login: Option<String>,
    /// The user password. For security reasons, TeamCity does not return the value of this field via `GET` requests. You can only use `PUT` requests to set new password values.
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// Returns **true** if the user has a regular password; otherwise, **false**. Users with no password cannot log in using the username/password credentials pair.
    #[serde(rename = "hasPassword", skip_serializing_if = "Option::is_none")]
    pub has_password: Option<bool>,
    /// This member supports the internal infrastructure and is not intended to be used directly from your code.
    #[serde(rename = "realm", skip_serializing_if = "Option::is_none")]
    pub realm: Option<String>,
    /// The relative (without the TeamCity server URL) link to this user.
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<models::Properties>>,
    #[serde(rename = "roles", skip_serializing_if = "Option::is_none")]
    pub roles: Option<Box<models::RoleAssignments>>,
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Box<models::Groups>>,
    /// The locator required to access this user. Only used for `POST` requests.
    #[serde(rename = "locator", skip_serializing_if = "Option::is_none")]
    pub locator: Option<String>,
    #[serde(rename = "avatars", skip_serializing_if = "Option::is_none")]
    pub avatars: Option<Box<models::UserAvatars>>,
    /// Returns **true** if the user configured the [two-factor user authentication](https://www.jetbrains.com/help/teamcity/managing-two-factor-authentication.html); otherwise, **false**.
    #[serde(rename = "enabled2FA", skip_serializing_if = "Option::is_none")]
    pub enabled2_fa: Option<bool>,
}

impl User {
    /// A TeamCity user account.
    pub fn new() -> User {
        User {
            username: None,
            name: None,
            id: None,
            email: None,
            last_login: None,
            password: None,
            has_password: None,
            realm: None,
            href: None,
            properties: None,
            roles: None,
            groups: None,
            locator: None,
            avatars: None,
            enabled2_fa: None,
        }
    }
}

