/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserApprovals : Represents a list of UserApprovalRule entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserApprovals {
    /// The number of UserApprovalRule objects in this collection.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The list of UserApprovalRule stored in this collection.
    #[serde(rename = "userApproval", skip_serializing_if = "Option::is_none")]
    pub user_approval: Option<Vec<models::UserApprovalRule>>,
}

impl UserApprovals {
    /// Represents a list of UserApprovalRule entities.
    pub fn new() -> UserApprovals {
        UserApprovals {
            count: None,
            user_approval: None,
        }
    }
}

