/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserLocator : Represents a locator string for filtering User entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserLocator {
    /// Username or 'current' for current user.
    #[serde(rename = "$singleValue", skip_serializing_if = "Option::is_none")]
    pub dollar_single_value: Option<String>,
    /// User group (direct or indirect parent) locator, includes the user considering group hierarchy.
    #[serde(rename = "affectedGroup", skip_serializing_if = "Option::is_none")]
    pub affected_group: Option<String>,
    /// For paginated calls, how many entities to return per page.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// User email.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// User group (direct parent) locator, includes the user directly.
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    /// User id.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// User's last login time formatted as 'yyyyMMddTHHmmss+ZZZZ'
    #[serde(rename = "lastLogin", skip_serializing_if = "Option::is_none")]
    pub last_login: Option<String>,
    /// User's display name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "property", skip_serializing_if = "Option::is_none")]
    pub property: Option<String>,
    /// User's role
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    /// For paginated calls, from which entity to start rendering the page.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i64>,
    /// Username of a user.
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl UserLocator {
    /// Represents a locator string for filtering User entities.
    pub fn new() -> UserLocator {
        UserLocator {
            dollar_single_value: None,
            affected_group: None,
            count: None,
            email: None,
            group: None,
            id: None,
            last_login: None,
            name: None,
            property: None,
            role: None,
            start: None,
            username: None,
        }
    }
}

