/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserGroupLocator : Represents a locator string for filtering Group entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserGroupLocator {
    /// Supply multiple locators and return a union of the results.
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<String>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl UserGroupLocator {
    /// Represents a locator string for filtering Group entities.
    pub fn new() -> UserGroupLocator {
        UserGroupLocator {
            item: None,
            key: None,
            name: None,
        }
    }
}

