/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VcsCheckStatus : Stores information on the last known remote repository check for new changes.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VcsCheckStatus {
    /// The status of the changes check.  * **finished** — the check for changes is complete, no new check is scheduled. * **scheduled** — the new check for changes is scheduled. * **started** — a check for changes is currently in progress.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// The authority that issued a check for changes request.   * **schedule** — a check for changes is initiated by the TeamCity server, as a part of default repository polling mechanism. * **build** — a default check for changes that preceds any new build starting. * **user** — a TeamCity user clicked the configuration's 'Check for pending changes' action in TeamCity UI. * **commit_hook** — a check for changes was triggered by a [post-commit webhook](https://www.jetbrains.com/help/teamcity/configuring-vcs-post-commit-hooks-for-teamcity.html).
    #[serde(rename = "requestorType", skip_serializing_if = "Option::is_none")]
    pub requestor_type: Option<String>,
    /// The time of the latest check entry.
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
}

impl VcsCheckStatus {
    /// Stores information on the last known remote repository check for new changes.
    pub fn new() -> VcsCheckStatus {
        VcsCheckStatus {
            status: None,
            requestor_type: None,
            timestamp: None,
        }
    }
}

