/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VcsLabels : Represents a list of VcsLabel entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VcsLabels {
    /// The current number of VcsLabel objects in this list.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The list of VcsLabels owned by this collection that satisfy the given locator.
    #[serde(rename = "vcsLabel", skip_serializing_if = "Option::is_none")]
    pub vcs_label: Option<Vec<models::VcsLabel>>,
}

impl VcsLabels {
    /// Represents a list of VcsLabel entities.
    pub fn new() -> VcsLabels {
        VcsLabels {
            count: None,
            vcs_label: None,
        }
    }
}

