/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VcsRootLocator : Represents a locator string for filtering VcsRoot entities.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VcsRootLocator {
    /// Project (direct or indirect parent) locator.
    #[serde(rename = "affectedProject", skip_serializing_if = "Option::is_none")]
    pub affected_project: Option<String>,
    /// For paginated calls, how many entities to return per page.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// Entity ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<i32>,
    /// Supply multiple locators and return a union of the results.
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<String>,
    /// Limit processing to the latest `<lookupLimit>` entities.
    #[serde(rename = "lookupLimit", skip_serializing_if = "Option::is_none")]
    pub lookup_limit: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Project (direct parent) locator.
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(rename = "property", skip_serializing_if = "Option::is_none")]
    pub property: Option<Property>,
    /// For paginated calls, from which entity to start rendering the page.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i32>,
    /// Type of VCS (e.g. jetbrains.git).
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
}

impl VcsRootLocator {
    /// Represents a locator string for filtering VcsRoot entities.
    pub fn new() -> VcsRootLocator {
        VcsRootLocator {
            affected_project: None,
            count: None,
            id: None,
            internal_id: None,
            item: None,
            lookup_limit: None,
            name: None,
            project: None,
            property: None,
            start: None,
            r#type: None,
            uuid: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Property {
    #[serde(rename = "exists")]
    Exists,
    #[serde(rename = "not-exists")]
    NotExists,
    #[serde(rename = "equals")]
    Equals,
    #[serde(rename = "does-not-equal")]
    DoesNotEqual,
    #[serde(rename = "starts-with")]
    StartsWith,
    #[serde(rename = "contains")]
    Contains,
    #[serde(rename = "does-not-contain")]
    DoesNotContain,
    #[serde(rename = "ends-with")]
    EndsWith,
    #[serde(rename = "any")]
    Any,
    #[serde(rename = "matches")]
    Matches,
    #[serde(rename = "does-not-match")]
    DoesNotMatch,
    #[serde(rename = "more-than")]
    MoreThan,
    #[serde(rename = "no-more-than")]
    NoMoreThan,
    #[serde(rename = "less-than")]
    LessThan,
    #[serde(rename = "no-less-than")]
    NoLessThan,
    #[serde(rename = "ver-more-than")]
    VerMoreThan,
    #[serde(rename = "ver-no-more-than")]
    VerNoMoreThan,
    #[serde(rename = "ver-less-than")]
    VerLessThan,
    #[serde(rename = "ver-no-less-than")]
    VerNoLessThan,
}

impl Default for Property {
    fn default() -> Property {
        Self::Exists
    }
}

