/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VersionedSettingsContextParameter : Represents a Versioned Settings Context Parameter.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionedSettingsContextParameter {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl VersionedSettingsContextParameter {
    /// Represents a Versioned Settings Context Parameter.
    pub fn new() -> VersionedSettingsContextParameter {
        VersionedSettingsContextParameter {
            name: None,
            value: None,
        }
    }
}

