/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VersionedSettingsStatus : Represents a Versioned Settings Status.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionedSettingsStatus {
    #[serde(rename = "dslOutdated", skip_serializing_if = "Option::is_none")]
    pub dsl_outdated: Option<bool>,
    #[serde(rename = "missingContextParameters", skip_serializing_if = "Option::is_none")]
    pub missing_context_parameters: Option<Vec<String>>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "versionedSettingsError", skip_serializing_if = "Option::is_none")]
    pub versioned_settings_error: Option<Vec<models::VersionedSettingsError>>,
}

impl VersionedSettingsStatus {
    /// Represents a Versioned Settings Status.
    pub fn new() -> VersionedSettingsStatus {
        VersionedSettingsStatus {
            dsl_outdated: None,
            missing_context_parameters: None,
            message: None,
            r#type: None,
            timestamp: None,
            versioned_settings_error: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "warn")]
    Warn,
}

impl Default for Type {
    fn default() -> Type {
        Self::Info
    }
}

