/*
 * TeamCity REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2018.1 (current)
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VersionedSettingsToken : Represents a Versioned Settings Token.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionedSettingsToken {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl VersionedSettingsToken {
    /// Represents a Versioned Settings Token.
    pub fn new() -> VersionedSettingsToken {
        VersionedSettingsToken {
            name: None,
            value: None,
            description: None,
        }
    }
}

